'use strict';
const {actor,service,json,fail,uuid}=require('./lib/portal-service'),calendar=require('./lib/dream-calendar');
const keys={plan:['title','description','ownerId','anchorDate','status'],milestone:['milestoneId','title','description','position','targetDate','status','progressNote'],task:['title','details','dueDate','assigneeIds','milestoneId'],meeting:['kind','startsAt','durationMinutes','timezone','attendeeIds'],complete:['meetingId','summary'],cancel:['meetingId'],retry_meeting:['meetingId']};
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;
const text=(v,n,required=false)=>typeof v==='string'&&v.length<=n&&(!required||v.trim().length>0)&&!/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v);
const ids=v=>Array.isArray(v)&&v.length>=1&&v.length<=50&&v.every(uuid)&&new Set(v).size===v.length;
function parse(event){if(event.isBase64Encoded||typeof event.body!=='string'||Buffer.byteLength(event.body)>18000)throw fail(400,'Check the pathway details.');let b;try{b=JSON.parse(event.body);}catch{throw fail(400,'Check the pathway details.');}const required=['action','applicantId','requestId','version',...(keys[b?.action]||[])];if(!Object.hasOwn(keys,b?.action)||Object.keys(b).length!==required.length||!required.every(k=>Object.hasOwn(b,k))||!uuid(b.applicantId)||!uuid(b.requestId)||!Number.isSafeInteger(b.version)||b.version<0)throw fail(400,'Check the pathway action.');
 let valid=true;
 if(b.action==='plan')valid=text(b.title,160,true)&&text(b.description,4000,true)&&uuid(b.ownerId)&&date(b.anchorDate)&&['active','paused'].includes(b.status);
 if(b.action==='milestone')valid=(b.milestoneId===null||uuid(b.milestoneId))&&text(b.title,160,true)&&text(b.description,3000,true)&&text(b.progressNote,3000)&&Number.isSafeInteger(b.position)&&b.position>=1&&b.position<=100&&(b.targetDate===null||date(b.targetDate))&&['planned','in_progress','completed','paused'].includes(b.status);
 if(b.action==='task')valid=text(b.title,160,true)&&text(b.details,4000,true)&&date(b.dueDate)&&ids(b.assigneeIds)&&b.assigneeIds.length<=30&&(b.milestoneId===null||uuid(b.milestoneId));
 if(b.action==='meeting'){valid=['quarterly','follow_up'].includes(b.kind)&&typeof b.startsAt==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(b.startsAt)&&Number.isFinite(Date.parse(b.startsAt))&&[30,45,60].includes(b.durationMinutes)&&ids(b.attendeeIds)&&text(b.timezone,100,true);try{new Intl.DateTimeFormat('en-US',{timeZone:b.timezone}).format();}catch{valid=false;}}
 if(['complete','cancel','retry_meeting'].includes(b.action))valid=uuid(b.meetingId)&&(b.action!=='complete'||text(b.summary,4000,true));if(!valid)throw fail(400,'Check the dates, staff selections, and required fields.');return b;
}
async function rpc(name,body){const r=await service('/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json().catch(()=>null);if(!r.ok)throw fail(v?.code==='42501'?403:['40001','23505'].includes(v?.code)?409:['22023','23514','22007','22008','22P02','23502'].includes(v?.code)?400:503,v?.code==='42501'?'You cannot access or change this private pathway.':v?.code==='40001'?'The pathway changed or a calendar update is still running. Refresh and try again.':v?.code==='23505'?'A request or quarterly meeting already exists. Refresh before trying again.':['22023','23514','22007','22008','22P02','23502'].includes(v?.code)?'Check the dates and required fields. A quarterly review cannot be recorded before its meeting starts.':'Dream Pathway is temporarily unavailable.');return v;}
async function handler(event){if(!['GET','POST'].includes(event.httpMethod))return json(405,{message:'Method not allowed.'});try{
 const q=event.queryStringParameters||{},multi=event.multiValueQueryStringParameters||{};let b,aid;
 if(event.httpMethod==='GET'){if(event.body||Object.keys(q).length!==1||!uuid(q.applicantId)||Object.entries(multi).some(([k,v])=>k!=='applicantId'||v.length!==1))throw fail(400,'Choose a Talent profile.');aid=q.applicantId;}
 else{if(Object.keys(q).length||Object.keys(multi).length||event.rawQueryString)throw fail(400,'Invalid request.');b=parse(event);aid=b.applicantId;}
 const uid=await actor(event);let pending=false;
 if(b){const saved=await rpc('change_dream_pathway',{p_actor_user_id:uid,p_body:b});if(saved.meetingId){try{const cmd=await rpc('claim_dream_calendar',{p_actor_user_id:uid,p_meeting_id:saved.meetingId,p_enabled:Boolean(calendar.configured()),p_organizer:calendar.organizer()});if(cmd){const result=await calendar.sync(cmd);pending=!(await rpc('finish_dream_calendar',{p_meeting_id:cmd.meetingId,p_lease_id:cmd.leaseId,p_result:result}));}}catch{pending=true;}}}
 const state=await rpc('get_dream_pathway',{p_actor_user_id:uid,p_applicant_id:aid});return json(pending?202:200,{...state,calendarSyncPending:pending});
 }catch(e){return json(e.status||503,{message:e.status?e.message:'Dream Pathway is temporarily unavailable.'});}}
module.exports={handler,parse,date,ids};
