'use strict';
const {actor,service,json,fail,uuid,config}=require('./lib/portal-service');
const {parseImage}=require('./support-tickets');
const bucket='soro-work-evidence';
function exact(v,keys){return v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));}
function date(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const n=new Date(v+'T00:00:00Z');return Number.isFinite(n.getTime())&&n.toISOString().slice(0,10)===v;}
function query(q){if(Object.keys(q).some(k=>!['placementId','from','to','offset','imageId'].includes(k)))throw fail(400,'Choose available work log filters.');if('imageId'in q){if(!exact(q,['imageId'])||!uuid(q.imageId))throw fail(400,'Choose a valid image.');return q;}if(q.placementId&&!uuid(q.placementId)||q.from&&!date(q.from)||q.to&&!date(q.to)||q.offset&&(!/^\d{1,6}$/.test(q.offset)||+q.offset>100000)||q.from&&q.to&&q.from>q.to)throw fail(400,'Choose valid dates and a placement.');return q;}
function dimensions(image){
 const b=image.bytes;let w=0,h=0;
 if(image.type==='image/png'){w=b.readUInt32BE(16);h=b.readUInt32BE(20);}
 if(image.type==='image/jpeg'){let pos=2;while(pos+9<b.length){if(b[pos]!==255)break;const marker=b[pos+1];if(marker===0xda||marker===0xd9)break;if(marker===0xff){pos++;continue;}const size=b.readUInt16BE(pos+2);if(size<2||pos+2+size>b.length)break;if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker)){h=b.readUInt16BE(pos+5);w=b.readUInt16BE(pos+7);break;}pos+=2+size;}}
 if(image.type==='image/webp'){const tag=b.toString('ascii',12,16);if(tag==='VP8X'&&b.length>=30){w=1+b.readUIntLE(24,3);h=1+b.readUIntLE(27,3);}else if(tag==='VP8L'&&b.length>=25&&b[20]===0x2f){w=1+(((b[22]&0x3f)<<8)|b[21]);h=1+(((b[24]&0xf)<<10)|(b[23]<<2)|(b[22]>>6));}else if(tag==='VP8 '&&b.length>=30&&b.subarray(23,26).equals(Buffer.from([0x9d,1,0x2a]))){w=b.readUInt16LE(26)&0x3fff;h=b.readUInt16LE(28)&0x3fff;}}
 if(!w||!h||w>12000||h>12000||w*h>40000000)throw fail(400,'Choose a screenshot no larger than 12,000 pixels per side or 40 megapixels.');return image;
}
function body(event){if(event.isBase64Encoded||typeof event.body!=='string'||Buffer.byteLength(event.body)>4300000)throw fail(413,'Use an image up to 3 MB.');let b;try{b=JSON.parse(event.body);}catch{throw fail(400,'Invalid work log action.');}const keys={request:['placementId','workDate','note'],share:['sessionId','note','image'],cancel:['id'],withdraw:['id']};if(!b||!Object.hasOwn(keys,b.action)||!exact(b,['action','requestId',...keys[b.action]])||!uuid(b.requestId))throw fail(400,'Choose a supported work log action.');if(b.action==='request'&&(!uuid(b.placementId)||!date(b.workDate))||b.action==='share'&&!uuid(b.sessionId)||['cancel','withdraw'].includes(b.action)&&!uuid(b.id))throw fail(400,'Choose a valid record.');if('note'in b){if(typeof b.note!=='string'||b.note.trim().length>500||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(b.note))throw fail(400,'Keep the work summary to 500 characters.');b.note=b.note.trim();}if(b.action==='share'){if(!b.image)throw fail(400,'Choose a screenshot.');b.image=dimensions(parseImage(b.image));}return b;}
function path(v){if(typeof v!=='string'||!/^([0-9a-f-]{36}\/){4}[0-9a-f]{64}\.(png|jpg|webp)$/.test(v)||!v.split('/').slice(0,4).every(uuid))throw fail(503,'The image reference could not be verified.');return `${bucket}/${v}`;}
function signedURL(raw){const origin=config().url;const u=new URL(raw?.startsWith('/object/')?'/storage/v1'+raw:raw,origin+'/storage/v1/');if(u.origin!==origin||!u.pathname.startsWith(`/storage/v1/object/sign/${bucket}/`))throw fail(503,'The image link could not be verified.');return u.href;}
async function rpc(name,data){const r=await service('/rest/v1/rpc/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const v=await r.json().catch(()=>null);if(!r.ok)throw fail(v?.code==='42501'?403:v?.code==='23505'?409:v?.code==='P0001'?429:['22023','22007','22008','22P02','23514'].includes(v?.code)?400:503,v?.code==='42501'?'Your account cannot access this work record.':v?.code==='23505'?'This request is already recorded or its details changed. Refresh before trying again.':v?.code==='P0001'?'The daily screenshot or request limit has been reached.':['22023','22007','22008','22P02','23514'].includes(v?.code)?'The dates or upload are invalid or expired. Check the details and try again.':'Work Log is temporarily unavailable.');return v;}
async function handler(event){if(!['GET','POST'].includes(event.httpMethod))return json(405,{message:'Method not allowed.'});try{const q=query(event.queryStringParameters||{});if(event.httpMethod==='GET'&&event.body||event.httpMethod==='POST'&&Object.keys(q).length)throw fail(400,'Unsupported request.');const b=event.httpMethod==='POST'?body(event):null;const user=await actor(event);if(event.httpMethod==='GET'){if(q.imageId){const i=await rpc('get_work_screenshot',{p_actor_user_id:user,p_id:q.imageId});const r=await service('/storage/v1/object/sign/'+path(i?.path),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expiresIn:60})});const v=await r.json().catch(()=>null);if(!r.ok||!v?.signedURL)throw fail(503,'The screenshot could not be opened.');return json(200,{url:signedURL(v.signedURL),expiresIn:60});}return json(200,await rpc('get_work_log',{p_actor_user_id:user,p_filters:q}));}
 if(b.action==='share'){const {image,...values}=b;delete values.action;const reserved=await rpc('change_work_log',{p_actor_user_id:user,p_action:'reserve',p_body:{...values,sha256:image.sha256,type:image.type,size:image.bytes.length}});if(!uuid(reserved?.id))throw fail(503,'The upload could not be prepared.');if(reserved.state!=='shared'){const r=await service('/storage/v1/object/'+path(reserved.path),{method:'POST',headers:{'Content-Type':image.type,'x-upsert':'false'},body:image.bytes});if(!r.ok){const v=await r.json().catch(()=>null);if(r.status!==409&&v?.error!=='Duplicate'&&String(v?.statusCode)!=='409')throw fail(503,'The screenshot was not shared. Retry this upload.');}}
  return json(200,await rpc('change_work_log',{p_actor_user_id:user,p_action:'finalize',p_body:{id:reserved.id,requestId:b.requestId}}));}
 const {action,...values}=b;return json(200,await rpc('change_work_log',{p_actor_user_id:user,p_action:action,p_body:values}));
 }catch(e){return json(e.status||503,{message:e.status?e.message:'Work Log is temporarily unavailable. Please try again.'});}}
module.exports={handler,_test:{date,query,body,dimensions,path,signedURL}};
