'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {applicantPortalNewsletter:mail}=require('../netlify/functions/lib/applicant-portal-newsletter');
test('newsletter uses the Talent reply mailbox, branded HTML and a first-name greeting',()=>{const d=mail({full_name:'Garin, Gabriel Anda'});assert.match(d.from,/talents@thesorogroup.com/);assert.equal(d.replyTo,'talents@thesorogroup.com');assert.match(d.html,/Hi Gabriel,/);assert.doesNotMatch(d.html,/Hi Garin|,,/);assert.match(d.html,/soro-logo-final-transparent/);assert.match(d.html,/<table/);assert.match(d.html,/mailto:talents@thesorogroup.com/);assert.match(d.text,/Hi Gabriel,/);});
test('newsletter covers preparation, privacy and conditional support without a funding promise',()=>{const d=mail({first_name:'Jamie'});for(const s of ['Quarterly Dream Check-Ins','completely optional','private by default','résumé','character references','button-up shirt with a tie','not automatic screen capture','not a promise of funding','not a client placement'])assert.ok(d.text.includes(s),s);assert.doesNotMatch(d.text,/\$200|guaranteed benefits|automatically enrolled/);assert.equal(Object.hasOwn(d,'to'),false);});
test('new-feature summary precedes details and Dream Pathway leads both',()=>{const d=mail();assert.match(d.subject,/new Soro Talent Portal/);const headings=Array.from(d.html.matchAll(/<h2[^>]*>(.*?)<\/h2>/g),m=>m[1]);assert.deepEqual(headings.slice(0,3),['What’s New at a Glance','NEW · Your Dream Pathway','NEW · Upload a photo of your “why”']);assert.match(d.text,/What’s New at a Glance\n\n- Dream Pathway/);assert.equal((d.html.match(/<ul /g)||[]).length,3);});
test('optional photo feature gives explicit navigation and purpose',()=>{const d=mail();for(const s of ['optional Inspiration Photo upload','photo of a meaningful moment','explaining why you do what you do','open My Profile','select Upload Inspiration Photo','What This Photo Means to You (Optional)','feature is available'])assert.ok(d.text.includes(s),s);});
test('new portal guidance distinguishes support from private feedback',()=>{const d=mail();for(const s of ['This portal is new','occasional glitch','? button at the top right','New ticket','Upload Image','Submit support ticket','Your tickets','Feedback near the bottom','privately to the Founder and Admin team','when you need help or a problem resolved','cannot sign in'])assert.ok(d.text.includes(s),s);assert.doesNotMatch(d.text,/guaranteed response|within 24 hours|Support Tickets sidebar/);});
test('the email ends with an actionable checklist, including optional photo and privacy',()=>{const d=mail(),i=d.text.indexOf('Your Portal To-Do Checklist');assert.ok(i>d.text.indexOf('A new portal, built better with you'));const checklist=d.text.slice(i);assert.equal((checklist.match(/\[ \]/g)||[]).length,7);assert.match(checklist,/Optional: use Upload Inspiration Photo/);assert.match(checklist,/Keep it private/);assert.match(checklist,/headshot/);assert.match(checklist,/references/);assert.match(d.html,/Your Portal To-Do Checklist/);});
test('closing checklist is a distinct high-contrast branded panel with email-safe background',()=>{const h=mail().html.match(/<td class="content newsletter-checklist"[\s\S]*?<\/td>/)?.[0];assert.ok(h);assert.match(h,/bgcolor="#0c294f"/);assert.match(h,/background:#0c294f;border-top:4px solid #ffb276/);assert.match(h,/color:#fff5e8/);assert.match(h,/color:#e1e8f1/);assert.match(h,/color:#ffb276/);assert.doesNotMatch(h,/#35495f|#fff5e8;border/);const lum=hex=>{const c=hex.match(/\w\w/g).map(v=>parseInt(v,16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};for(const color of ['fff5e8','e1e8f1','ffb276'])assert.ok((lum(color)+.05)/(lum('0c294f')+.05)>=4.5,color);});
