'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const api=require('../netlify/functions/dream-pathway'),ui=require('../operations/dream-pathway'),cal=require('../netlify/functions/lib/dream-calendar'),detail=require('../operations/task-detail');
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const base={applicantId:id(1),requestId:id(2),version:0};
const plan={...base,action:'plan',title:'Finish Education',description:'Choose a practical program.',ownerId:id(3),anchorDate:'2026-12-15',status:'active'};
const parse=b=>api.parse({body:JSON.stringify(b)});
test('Dream actions reject unknown keys, invalid dates and empty required fields',()=>{assert.deepEqual(parse(plan),plan);for(const p of [{actorId:id(4)},{title:''},{description:''},{anchorDate:'2026-02-30'},{status:'approved'},{ownerId:'not-id'},{version:-1}])assert.throws(()=>parse({...plan,...p}));});
test('milestones and staff follow-ups use bounded exact fields',()=>{
 const m={...base,action:'milestone',milestoneId:null,title:'Compare Programs',description:'Three options',position:1,targetDate:null,status:'planned',progressNote:''};assert.deepEqual(parse(m),m);for(const p of [{position:0},{position:101},{status:'done'},{progressNote:'a'.repeat(3001)}])assert.throws(()=>parse({...m,...p}));
 const t={...base,action:'task',title:'Research programs',details:'Compare schedules',dueDate:'2026-10-01',assigneeIds:[id(3),id(4)],milestoneId:null};assert.deepEqual(parse(t),t);for(const p of [{assigneeIds:[]},{assigneeIds:[id(3),id(3)]},{assigneeIds:Array.from({length:31},(_,n)=>id(n+30))},{details:''}])assert.throws(()=>parse({...t,...p}));
});
const command={action:'create',transactionId:id(8),organizerId:'talents@example.test',startsAt:'2026-12-15T15:00:00Z',durationMinutes:30,timezone:'America/Chicago',attendees:[{name:'Jamie',email:'jamie@example.test'},{name:'Morgan',email:'morgan@example.test'},{name:'Duplicate',email:'JAMIE@example.test'}]};
test('meeting request requires timezone and multiple attendees are supported',()=>{const b={...base,action:'meeting',kind:'quarterly',startsAt:command.startsAt,durationMinutes:30,timezone:command.timezone,attendeeIds:[id(3),id(4)]};assert.deepEqual(parse(b),b);for(const p of [{attendeeIds:[]},{timezone:'Bad/Zone'},{durationMinutes:10},{kind:'interview'},{startsAt:'invalid'}])assert.throws(()=>parse({...b,...p}));});
test('calendar is branded, private, deduplicated and does not expose Dream notes',()=>{const b=cal.eventBody({...command,dream:'SECRET DREAM',summary:'SECRET SUMMARY',description:'SECRET DESCRIPTION'});assert.equal(b.attendees.length,2);assert.equal(b.transactionId,id(8));assert.equal(b.sensitivity,'private');assert.equal(b.end.dateTime,'2026-12-15T15:30:00.000');for(const s of ['Philippine Time','America/Chicago','mailto:talents@thesorogroup.com','confidential meeting invitation from The Soro Group'])assert.ok(b.body.content.includes(s),s);assert.doesNotMatch(JSON.stringify(b),/SECRET|Soro Ops|interview.result/i);});
test('safe meeting links accept only known Teams hosts',()=>{assert.ok(cal.safeJoin('https://teams.microsoft.com/l/meetup-join/abc'));for(const u of ['javascript:alert(1)','https://teams.microsoft.com.evil.test/','http://teams.microsoft.com/','https://evil.test/','https://user:pass@teams.microsoft.com/'])assert.equal(cal.safeJoin(u),null);});
function state(){return{canManage:true,plan:{id:id(7),title:'Education <script>',description:'Our path',ownerName:'Morgan',nextReviewOn:'2026-12-15',status:'active'},milestones:[{id:id(5),title:'Research',description:'Compare options',status:'completed'},{id:id(6),title:'Enroll',description:'Apply',status:'planned'}],tasks:[{id:id(9),title:'Private research',dueDate:'2026-10-01',status:'open',canOpen:false}],meetings:[],history:[{summary:'Private audit',actorName:'Morgan',at:'2026-09-13'}]};}
test('profile markers reflect saved milestone progress and escape text',()=>{const h=ui.summary(state());assert.match(h,/1 of 2 milestones reached/);assert.match(h,/Education &lt;script&gt;/);assert.match(h,/Next Step/);assert.match(h,/Enroll/);assert.doesNotMatch(h,/Private research|<script>/);});
test('Talent view does not render staff actions, tasks or internal history',()=>{const h=ui.markup({...state(),canManage:false});assert.doesNotMatch(h,/Private research|Private audit|Edit Milestone|Schedule Meeting|Add Follow-Up Task|Research & Follow-Ups/);assert.match(h,/Compare options/);});
test('task links respect access and meetings reflect cancellation and recording eligibility',()=>{const d=state();d.meetings=[{id:id(10),kind:'quarterly',status:'scheduled',startsAt:'2099-01-01T12:00:00Z',durationMinutes:30,timezone:'UTC',calendarStatus:'synced',attendeeNames:[]},{id:id(11),kind:'follow_up',status:'cancelled',startsAt:command.startsAt,durationMinutes:30,timezone:'UTC',calendarStatus:'synced'}];const h=ui.markup(d);assert.doesNotMatch(h,new RegExp('href="#tasks/'+id(9)));assert.match(h,/disabled title="Available after the synced meeting starts"/);assert.match(h,/Calendar cancellation complete/);});
test('Dream tasks have a direct source link and quarterly explanation',()=>{const h=detail.markup({task:{title:'Dream reminder',kind:'staff_task',source:{kind:'dream_pathway',applicantId:id(1),reviewCycle:0},assignees:[]},history:[]});assert.match(h,/Open Dream Pathway/);assert.match(h,/Record the quarterly check-in in Benefits/);});
test('Graph pre-create failure is distinguished from uncertain create failure',async()=>{const old=global.fetch,tenant=process.env.MICROSOFT_TENANT_ID;process.env.MICROSOFT_TENANT_ID='test';try{global.fetch=async()=>{throw Error('token unavailable')};assert.equal((await cal.sync(command)).notCreated,true);let calls=0;global.fetch=async()=>{if(++calls===1)return new Response(JSON.stringify({access_token:'mock'}));throw Error('lost create response')};assert.equal((await cal.sync(command)).notCreated,undefined);}finally{global.fetch=old;process.env.MICROSOFT_TENANT_ID=tenant;}});
test('Graph create/read/cancel retain event identity and stable transaction ID',async()=>{const old=global.fetch,tenant=process.env.MICROSOFT_TENANT_ID;process.env.MICROSOFT_TENANT_ID='test';try{const calls=[];global.fetch=async(url,o)=>{calls.push({url,o});return new Response(JSON.stringify(String(url).includes('/token')?{access_token:'mock'}:{id:'event-one',onlineMeeting:{joinUrl:'https://teams.microsoft.com/l/test'}}));};assert.equal((await cal.sync(command)).status,'synced');assert.equal(JSON.parse(calls[1].o.body).transactionId,command.transactionId);calls.length=0;await cal.sync({...command,action:'read',eventId:'event-one'});assert.equal(calls[1].o.method,undefined);calls.length=0;assert.equal((await cal.sync({...command,action:'cancel',eventId:'event-one'})).status,'synced');assert.ok(calls[1].url.endsWith('/event-one/cancel'));}finally{global.fetch=old;process.env.MICROSOFT_TENANT_ID=tenant;}});
test('calendar sending is disabled outside production',()=>{const old={...process.env};try{for(const k of ['MICROSOFT_TENANT_ID','MICROSOFT_CLIENT_ID','MICROSOFT_CLIENT_SECRET','MICROSOFT_SHARED_ORGANIZER_USER_ID'])process.env[k]='mock';for(const c of ['deploy-preview','dev','branch-deploy']){process.env.CONTEXT=c;assert.equal(cal.configured(),false);}process.env.CONTEXT='production';assert.ok(cal.configured());}finally{for(const k of Object.keys(process.env))if(!(k in old))delete process.env[k];Object.assign(process.env,old);}});
test('database locks private state and preserves calendar uncertainty and quarterly identity',()=>{const s=fs.readFileSync('supabase/migrations/20260913_075_dream_pathway.sql','utf8');for(const part of ['dream_review_task_once','dream_quarter_meeting_once','not calendar_prior_attempted','calendar_request_id=p_lease_id','task_json_before_dream','dream_retirement_guard','read_at=null,created_at=clock_timestamp()','portal_access_status=\'active\''])assert.ok(s.includes(part),part);assert.doesNotMatch(s,/grant .* to authenticated/);assert.match(s,/review_cycle=review_cycle\+1/);});
test('a saved meeting still returns saved state when calendar claiming fails',async()=>{const service=require('../netlify/functions/lib/portal-service'),context={module:{exports:{}},Buffer,URLSearchParams,Intl,Date,Object,JSON,Number,String,Set,Error,require:name=>name==='./lib/portal-service'?{...service,actor:async()=>id(3),service:async url=>{if(url.endsWith('/change_dream_pathway'))return new Response(JSON.stringify({meetingId:id(8)}));if(url.endsWith('/claim_dream_calendar'))throw Error('Temporary connection failure');if(url.endsWith('/get_dream_pathway'))return new Response(JSON.stringify(state()));throw Error('Unexpected call');}}:{configured:()=>false,organizer:()=>''}};vm.runInNewContext(fs.readFileSync('netlify/functions/dream-pathway.js','utf8'),context);const r=await context.module.exports.handler({httpMethod:'POST',body:JSON.stringify({...base,action:'cancel',meetingId:id(8)})});assert.equal(r.statusCode,202);assert.equal(JSON.parse(r.body).calendarSyncPending,true);assert.equal(JSON.parse(r.body).plan.title,state().plan.title);});
test('session-bound requests and dashboard link use the current Talent profile',()=>{const s=fs.readFileSync('operations/dream-pathway.js','utf8');assert.match(s,/client!==w.soroSupabase\|\|captured!==scope\(\)/);assert.match(s,/data.session.user\?\.id!==uid/);assert.match(fs.readFileSync('operations/operations.js','utf8'),/\['Dream Pathway','View Plan','Milestones and upcoming check-ins'/);});
test('Test Mode supports isolated pathways shared between management and Talent',async()=>{const w={parent:{postMessage(){}},history:{replaceState(){}},addEventListener(){}},context={window:w,document:{addEventListener(){}},URL,Response,Map,Promise,Object,JSON,Error,Date,Intl,crypto:require('node:crypto').webcrypto};vm.runInNewContext(fs.readFileSync('operations/test-mode/runtime.js','utf8'),context);const session=w.SoroTestSession,aid=session.id(10),endpoint='/.netlify/functions/dream-pathway';session.select('talent');let r=await w.fetch(endpoint,{method:'POST',body:JSON.stringify({...plan,applicantId:aid,ownerId:session.id(2)})});assert.equal(r.status,200);let d=await r.json();assert.equal(d.tasks.length,1);session.select('va');d=await(await w.fetch(endpoint+'?applicantId='+aid)).json();assert.equal(d.canManage,false);assert.equal(d.tasks.length,0);assert.equal(d.plan.title,plan.title);r=await w.fetch(endpoint,{method:'POST',body:JSON.stringify({...plan,applicantId:aid,requestId:id(99)})});assert.equal(r.status,403);session.select('sales');assert.equal((await w.fetch(endpoint+'?applicantId='+aid)).status,403);session.reset();session.select('talent');d=await(await w.fetch(endpoint+'?applicantId='+aid)).json();assert.equal(d.plan,null);});
