'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const api=require('../netlify/functions/dream-inspiration'),ui=require('../operations/dream-inspiration'),{inspirationImage}=require('../netlify/functions/lib/inspiration-image');
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`,parse=b=>api.parse({body:JSON.stringify(b)});
const share={action:'share',applicantId:id(1),placementId:id(2),clientId:id(3),version:0,shareDream:true,sharePhoto:false,approvedStory:'Finish education',consentNote:'Talent approved the exact content'};
test('inspiration consent requires exact current content and Client identity',()=>{assert.deepEqual(parse(share),share);for(const p of [{actorId:id(2)},{clientId:null},{approvedStory:null},{approvedStory:'a'.repeat(20001)},{consentNote:''},{shareDream:'yes'},{version:-1}])assert.throws(()=>parse({...share,...p}));const missing={...share};delete missing.approvedStory;assert.throws(()=>parse(missing));});
test('captions are bounded and internal storage actions cannot be called through HTTP',()=>{assert.equal(parse({action:'caption',applicantId:id(1),version:2,caption:''}).caption,'');for(const action of ['reserve','finalize','delete','download'])assert.throws(()=>parse({action,applicantId:id(1),version:0}));assert.throws(()=>parse({action:'caption',applicantId:id(1),version:0,caption:'a'.repeat(501)}));});
test('storage path never accepts arbitrary bucket or traversal',()=>{assert.equal(api.path([id(1),id(2),id(3)+'.jpg'].join('/')),'soro-dream-inspiration/'+[id(1),id(2),id(3)+'.jpg'].join('/'));for(const s of ['../private','https://evil.test/a',id(1)+'/x.jpg','a/b/c.png'])assert.throws(()=>api.path(s));});
function jpg(){const frame=Buffer.from([255,192,0,17,8,0,100,0,100,3,1,17,0,2,17,0,3,17,0]);return Buffer.concat([Buffer.from([255,216]),frame,Buffer.from([255,218,0,8,1,1,0,0,63,0,0,255,217])]);}
test('photo boundary strips EXIF GPS and comments before storage hashing',()=>{const raw=jpg(),metadata=Buffer.from('Exif\0\0GPS SECRET'),comment=Buffer.from('private comment'),segment=(marker,v)=>{const h=Buffer.alloc(4);h[0]=255;h[1]=marker;h.writeUInt16BE(v.length+2,2);return Buffer.concat([h,v]);};const withMeta=Buffer.concat([raw.subarray(0,2),segment(225,metadata),segment(254,comment),raw.subarray(2)]);const clean=inspirationImage({type:'image/jpeg',dataBase64:withMeta.toString('base64')});assert.ok(clean.bytes.equals(raw));assert.equal(clean.sha256,inspirationImage({type:'image/jpeg',dataBase64:raw.toString('base64')}).sha256);assert.doesNotMatch(clean.bytes.toString(),/SECRET|private comment/);});
test('photo boundary rejects unexpected frames, malformed segments and wrong types',()=>{for(const b of [Buffer.from([255,216,255,225,255,255,255,217]),Buffer.from([255,216,255,217]),Buffer.from('<svg/>')])assert.throws(()=>inspirationImage({type:'image/jpeg',dataBase64:b.toString('base64')}));const p=jpg();p[3]=194;assert.throws(()=>inspirationImage({type:'image/jpeg',dataBase64:p.toString('base64')}));});
test('private presentation is escaped, optional, and uses role-specific controls',()=>{const h=ui.markup({caption:'<script>',photoId:id(1),canUpload:true,canShare:true,placements:[]},'blob:sample');assert.match(h,/&lt;script&gt;/);assert.match(h,/Private · Only you/);assert.match(h,/Replace Photo/);assert.match(h,/Client Sharing/);assert.doesNotMatch(ui.markup({canUpload:false,canShare:true}),/data-di-upload|data-di-remove/);assert.match(ui.guidance,/completely optional/);});
test('only private image links can render',()=>{assert.ok(ui.validPhoto('blob:sample'));assert.ok(ui.validPhoto('https://sample.supabase.co/storage/v1/object/sign/soro-dream-inspiration/a'));for(const u of ['javascript:alert(1)','https://evil.test/x','https://sample.supabase.co/storage/v1/object/public/a'])assert.equal(ui.validPhoto(u),false);});
test('production component prepares input without metadata and cleans up stale dialogs',()=>{const s=fs.readFileSync('operations/dream-inspiration.js','utf8');for(const needle of ["canvas.toDataURL('image/jpeg',.88)",'URL.revokeObjectURL(local)','dialogs.forEach(d=>{d.close();d.remove();})','scope===identity()&&client===w.soroSupabase','b.approvedStory=b.shareDream?data.story','b.clientId=data.placements.find'])assert.ok(s.includes(needle),needle);});
test('photo SQL keeps private grants and invalidates old Client and replacement consent',()=>{const s=fs.readFileSync('supabase/migrations/20260913_076_dream_inspiration.sql','utf8');for(const needle of ["p_body->>'approvedStory' is distinct from t.greatest_dream",'set active=false where applicant_id=aid and client_id=p.client_id','revoke_dream_sharing_on_placement_change','p.client_id=x.client_id','set photo_id=null,caption=\'\',active=story<>\'\''])assert.ok(s.includes(needle),needle);assert.doesNotMatch(s,/grant .* to authenticated/);});
test('Test Mode shares only opted-in sample content using the displayed Client identity and resets privately',async()=>{const w={parent:{postMessage(){}},history:{replaceState(){}},addEventListener(){}},context={window:w,document:{addEventListener(){}},URL,Response,Blob,Uint8Array,atob,Map,Promise,Object,JSON,Error,Date,Intl,crypto:require('node:crypto').webcrypto};vm.runInNewContext(fs.readFileSync('operations/test-mode/runtime.js','utf8'),context);const sess=w.SoroTestSession,aid=sess.id(10),ep='/.netlify/functions/dream-inspiration',get=()=>w.fetch(ep+'?applicantId='+aid),post=b=>w.fetch(ep,{method:'POST',body:JSON.stringify(b)});sess.select('va');let d=await(await get()).json();assert.equal(d.placements[0].clientId,sess.id(50));const body={...share,applicantId:aid,placementId:d.placements[0].id,clientId:d.placements[0].clientId,approvedStory:d.story};assert.equal((await post({...body,approvedStory:'stale'})).status,400);assert.equal((await post(body)).status,200);sess.select('client');assert.equal((await get()).status,403);d=await(await w.fetch(ep+'?applicantId='+aid+'&shared=true')).json();assert.ok(d.shared&&d.story);assert.equal(d.photoId,null);sess.reset();d=await(await w.fetch(ep+'?applicantId='+aid+'&shared=true')).json();assert.equal(d.shared,false);});
