'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {webcrypto}=require('node:crypto');
const runtime=fs.readFileSync('operations/test-mode/runtime.js','utf8');
function sandbox(){const messages=[],c={parent:{postMessage:v=>messages.push(v)},document:{addEventListener(){}},history:{replaceState(){}},URL,Response,crypto:webcrypto,console,Date};c.window=c;vm.createContext(c);vm.runInContext(runtime,c);c.soroScreeningPresentation=require('../operations/screening-presentation.js');return c;}
test('sample Client dashboard validates through the production renderer',async()=>{const c=sandbox(),data=await(await c.fetch('/.netlify/functions/client-dashboard')).json();assert.equal(require('../operations/client-dashboard.js').normalizeWorkspace(data,'client_admin').talent.length,1);});
test('sample contact edits are shared with Sales and Reset clears them',async()=>{const c=sandbox();await c.fetch('/.netlify/functions/client-profile',{method:'PATCH',body:JSON.stringify({contact:{fullName:'Alex Sample Carter'}})});assert.equal(c.SoroTestSession.store.clients[0].primaryContact.name,'Alex Sample Carter');assert.equal((await(await c.fetch('/.netlify/functions/client-dashboard')).json()).contactName,'Alex Sample Carter');c.SoroTestSession.reset();assert.equal((await(await c.fetch('/.netlify/functions/client-profile')).json()).profile.contact.fullName,'Alex Carter');});
test('sample workday keeps stable timestamps and appears in matched Client Work Log',async()=>{const c=sandbox();c.SoroTestSession.select('va');const post=action=>c.fetch('/.netlify/functions/talent-attendance',{method:'POST',body:JSON.stringify({action})});await post('start_day');const started=c.SoroTestSession.store.startedAt;await post('start_day');assert.equal(c.SoroTestSession.store.startedAt,started);await post('check_out');c.SoroTestSession.select('client');const log=require('../operations/work-log.js').validate(await(await c.fetch('/.netlify/functions/work-log')).json());assert.equal(log.sessions[0].startedAt,started);assert.ok(log.sessions[0].checkedOutAt);assert.equal(log.placements[0].canRequest,true);});
test('sample New markers have separate view receipts for each person',async()=>{const c=sandbox(),read=async()=>(await(await c.fetch('/.netlify/functions/tasks')).json()).tasks[0];c.SoroTestSession.select('va');assert.equal((await read()).isNew,true);await c.fetch('/.netlify/functions/task-detail',{method:'POST',body:JSON.stringify({action:'view',taskId:c.SoroTestSession.id(30)})});assert.equal((await read()).isNew,false);c.SoroTestSession.select('talent');assert.equal((await read()).isNew,true);});
test('queue metadata uses current review schema and saved sample skills/results',async()=>{const c=sandbox();c.SoroTestSession.select('talent');const read=async()=>require('../operations/talent-review-queue.js').normalizePayload(await(await c.fetch('/.netlify/functions/talent-review-queue')).json(),'talent_management');assert.equal((await read()).applicants[0].checklist.find(i=>i.key==='skills').verifiedSkillsCount,0);const a=c.SoroTestSession.store.applicants[1];await c.soroSupabase.from('applicants').update({verified_skills:['Calendar management'],english_test_result:'95'}).eq('id',a.id);const q=await read();assert.equal(q.applicants[0].checklist.find(i=>i.key==='skills').verifiedSkillsCount,1);assert.equal(q.applicants[0].checklist.find(i=>i.key==='english').resultRecorded,true);});
test('test roles cannot edit another role’s profile and task list stays scoped',async()=>{const c=sandbox();c.SoroTestSession.select('va');const result=await c.soroSupabase.from('applicants').update({full_name:'changed'}).eq('id',c.SoroTestSession.id(10));assert.ok(result.error);const work=await(await c.fetch('/.netlify/functions/task-detail',{method:'POST',body:JSON.stringify({action:'workspace'})})).json();assert.equal(work.tasks.length,1);assert.equal(work.tasks[0].title,'Review your sample profile');c.SoroTestSession.select('sales');const sales=await(await c.fetch('/.netlify/functions/tasks')).json();assert.equal(sales.tasks.length,1);assert.equal(sales.tasks[0].title,'Review client requirements');});
test('unlisted endpoints and external URLs are denied, with no native fetch fallback',async()=>{const c=sandbox();assert.equal((await c.fetch('https://thesorogroup.com/.netlify/functions/tasks')).status,403);assert.equal((await c.fetch('/.netlify/functions/send-email',{method:'POST'})).status,409);assert.throws(()=>new c.XMLHttpRequest());assert.throws(()=>new c.WebSocket());assert.doesNotMatch(runtime,/nativeFetch|originalFetch/);});
test('reset discards changes and pending data operations cannot mutate the new store',async()=>{const c=sandbox();c.SoroTestSession.select('talent');const pending=c.soroSupabase.from('applicants').update({full_name:'Unexpected'});c.SoroTestSession.store.contactName='Changed';c.SoroTestSession.reset();assert.ok((await pending).error);assert.equal(c.SoroTestSession.store.contactName,'Alex Carter');assert.equal(c.SoroTestSession.store.applicants[0].full_name,'Cruz, Jamie');});
test('task view receipt and progress persist only inside the sample session',async()=>{const c=sandbox();c.SoroTestSession.select('va');const send=body=>c.fetch('/.netlify/functions/task-detail',{method:'POST',body:JSON.stringify(body)}),taskId=c.SoroTestSession.id(30);await send({action:'view',taskId});await send({action:'save',taskId,patch:{progress:'in_progress',note:'Sample update'}});const t=await(await send({action:'get',taskId})).json();assert.equal(t.task.isUnread,false);assert.equal(t.task.progress,'in_progress');assert.equal(t.history.length,1);c.SoroTestSession.reset();assert.equal(c.SoroTestSession.store.tasks[0].progress,'not_started');});
test('Founder launcher keeps the child opaque and blocks outgoing connections',()=>{const source=fs.readFileSync('operations/founder-test-mode.js','utf8');assert.match(source,/setAttribute\('sandbox','allow-scripts allow-forms'\)/);assert.doesNotMatch(source,/allow-same-origin|allow-popups|allow-top-navigation/);assert.match(source,/connect-src 'none'/);assert.match(source,/form-action 'none'/);assert.match(source,/actor=root.soroCurrentAccess.user_id/);assert.match(source,/event.source!==frame\?\.contentWindow/);assert.match(source,/frame.srcdoc=frame.srcdoc/);});

test('sample check-ins share history and recurring tasks while preserving role privacy',async()=>{const c=sandbox(),id=c.SoroTestSession.id,endpoint='/.netlify/functions/placement-checkins',get=async(q='placementId='+id(21))=>{const r=await c.fetch(endpoint+'?'+q);return{status:r.status,data:await r.json()};},post=async(body)=>{const r=await c.fetch(endpoint,{method:'POST',body:JSON.stringify(body)});assert.equal(r.status,200);return r.json();};
 c.SoroTestSession.select('client');assert.equal((await get()).status,403);c.SoroTestSession.select('talent');let v=(await get()).data;assert.equal(require('../operations/placement-checkins').validate(v).notes.length,0);
 await post({action:'schedule',requestId:id(40),placementId:id(21),side:'talent',ownerId:id(2),version:0,cadenceDays:7,nextDue:v.today,enabled:true});v=(await get()).data;const plan=v.plans[0];
 const body={action:'record',requestId:id(41),placementId:id(21),side:'talent',planId:plan.id,planVersion:plan.version,version:0,noteId:null,observedOn:v.today,kind:'positive',source:'staff',summary:'Clear sample handoff',details:'Fictional context only',outcome:'going_well',nextAction:'Continue',followUpOn:null,correctionReason:null};await post(body);await post(body);
 v=(await get('applicantId='+id(10))).data;assert.equal(v.notes.length,1);assert.ok(v.plans[0].nextDue>v.today);assert.equal(c.SoroTestSession.store.tasks.filter(t=>t.source?.kind==='placement_checkin'&&t.status==='open').length,1);
 c.SoroTestSession.select('sales');assert.equal((await get()).data.notes.length,0);assert.equal((await get('applicantId='+id(10))).status,403);c.SoroTestSession.select('va');assert.equal((await get()).status,403);c.SoroTestSession.reset();c.SoroTestSession.select('talent');assert.equal((await get()).data.notes.length,0);
});
test('Founder gate rejects anonymous, inactive, ordinary Admin and other roles without writes',async()=>{const {handler}=require('../netlify/functions/founder-test-mode.js');const priorFetch=global.fetch,priorUrl=process.env.SUPABASE_URL,priorKey=process.env.SUPABASE_SERVICE_ROLE_KEY;process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='sb_secret_fake';try{assert.equal((await handler({httpMethod:'POST',body:'{}',headers:{}})).statusCode,401);for(const [access,status] of [[{role:'admin',is_founder:true,active:true,must_change_password:false},200],[{role:'admin',is_founder:false,active:true,must_change_password:false},403],[{role:'admin',is_founder:true,active:false,must_change_password:false},403],[{role:'sales',is_founder:true,active:true,must_change_password:false},403]]){const calls=[];global.fetch=async(url,options)=>{calls.push(options);return new Response(JSON.stringify(url.includes('/auth/')?{id:'f0000000-0000-4000-8000-000000000001'}:[access]),{status:200});};const r=await handler({httpMethod:'POST',body:'{}',headers:{authorization:'Bearer mock'}});assert.equal(r.statusCode,status);assert.ok(calls.every(c=>!c.method||c.method==='GET'));}}finally{global.fetch=priorFetch;if(priorUrl===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=priorUrl;if(priorKey===undefined)delete process.env.SUPABASE_SERVICE_ROLE_KEY;else process.env.SUPABASE_SERVICE_ROLE_KEY=priorKey;}});
