'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const api=require('../netlify/functions/placement-checkins'),ui=require('../operations/placement-checkins');
const id=n=>`10000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const schedule={action:'schedule',requestId:id(1),placementId:id(2),side:'talent',version:0,ownerId:id(3),nextDue:'2026-09-12',cadenceDays:7,enabled:true};
const record={action:'record',requestId:id(1),placementId:id(2),side:'talent',version:0,noteId:null,planId:null,planVersion:0,observedOn:'2026-09-12',kind:'positive',source:'staff',summary:'Helpful handoff',details:'Specific factual context.',outcome:'going_well',nextAction:'Continue this approach.',followUpOn:null,correctionReason:null};
const parse=b=>api.parse({body:JSON.stringify(b)});
test('schedule and observation accept only exact bounded envelopes',()=>{assert.deepEqual(parse(schedule),schedule);assert.deepEqual(parse(record),record);for(const b of [{...schedule,actorId:id(4)},{...schedule,cadenceDays:2},{...schedule,nextDue:'2026-02-30'},{...schedule,enabled:'true'},{...record,summary:''},{...record,details:'x'.repeat(4001)},{...record,source:'verified'},{...record,side:'admin'},{...record,version:1},{...record,followUpOn:'2026-13-01'}])assert.throws(()=>parse(b));});
test('correction requires reason, existing entry and version; it cannot complete a task',()=>{const b={...record,action:'correct',noteId:id(9),version:1,correctionReason:'Clarify source'};assert.deepEqual(parse(b),b);for(const patch of [{correctionReason:''},{version:0},{noteId:null},{planId:id(5)},{planVersion:1}])assert.throws(()=>parse({...b,...patch}));});
test('history queries reject identity injection, duplicates, invalid dates and mixed scopes',()=>{assert.deepEqual(api.query({queryStringParameters:{applicantId:id(1)}}),{applicantId:id(1)});for(const q of [{placementId:id(1),applicantId:id(2)},{placementId:id(1),role:'admin'},{placementId:id(1),from:'2026-02-30'},{placementId:id(1),from:'2026-09-12',to:'2026-09-11'},{placementId:id(1),offset:'-1'}])assert.throws(()=>api.query({queryStringParameters:q}));assert.throws(()=>api.query({queryStringParameters:{placementId:id(1)},rawQueryString:`placementId=${id(1)}&placementId=${id(2)}`}));});
function workspace(){return{viewerRole:'admin',today:'2026-09-12',subject:'talent',talentName:'Sample <Talent>',placements:[],plans:[],notes:[],total:0};}
test('private UI denies Client, Talent, inactive, password-gated and role-preview access',()=>{const source=fs.readFileSync('operations/placement-checkins.js','utf8'),context={module:{exports:{}},soroCurrentAccess:{role:'admin',active:true}};vm.runInNewContext(source,context);const access=context.module.exports;assert.equal(access.allowed(),true);for(const role of ['client_admin','client_reviewer','virtual_assistant','billing']){context.soroCurrentAccess.role=role;assert.equal(access.allowed(),false);}context.soroCurrentAccess={role:'admin',active:false};assert.equal(access.allowed(),false);context.soroCurrentAccess={role:'admin',must_change_password:true};assert.equal(access.allowed(),false);context.soroCurrentAccess={role:'admin'};context.adminPreviewingNonAdminWorkspace=()=>true;assert.equal(access.allowed(),false);});
test('history markup escapes notes and shows material previous versions',()=>{const v=workspace(),n={...record,id:id(8),clientName:'<Client>',version:2,authorName:'Sample Author',recordedAt:'2026-09-12',canCorrect:true,summary:'<script>bad()</script>',correctionReason:'Corrected source',revisions:[{...record,version:1,kind:'coaching',source:'client',outcome:'follow_up',authorName:'Earlier Author',recordedAt:'2026-09-11',followUpOn:'2026-09-20',correctionReason:'Earlier clarification'}]};v.notes=[n];v.total=1;const html=ui.markup(ui.validate(v));assert.doesNotMatch(html,/<script>/);for(const text of ['&lt;script&gt;','Correction History','Coaching Opportunity','Client Feedback','Needs Follow-up','Continue this approach.','Earlier clarification','Corrected source','Sample &lt;Talent&gt;'])assert.ok(html.includes(text),text);});
test('response roles, invalid notes and excessive pages fail closed',()=>{assert.equal(ui.validate(workspace()).subject,'talent');for(const patch of [{viewerRole:'virtual_assistant'},{notes:Array(31).fill({})},{today:'2026-02-30'},{notes:[{...record,id:'bad'}]}])assert.throws(()=>ui.validate({...workspace(),...patch}));});
test('source integration includes real profile and placement routes, immediate cleanup and managed task refresh',()=>{const s=fs.readFileSync('operations/placement-checkins.js','utf8');for(const token of ['soro-auth-changed','MutationObserver','initialRoute','soroTaskCenter?.refresh','soroTaskDetail?.close','controls.map(el=>el.disabled)'])assert.ok(s.includes(token),token);assert.match(fs.readFileSync('operations/talent-file-tabs.js','utf8'),/tabButton\('performance','Performance'\)/);assert.match(fs.readFileSync('operations/client-placement-workflow.js','utf8'),/data-placement-checkins/);});
test('private database surface has no browser grants and retained system history',()=>{const sql=fs.readFileSync('supabase/migrations/20260912_073_placement_checkins.sql','utf8');assert.match(sql,/for share/);assert.match(sql,/checkin_lock_owners/);assert.match(sql,/q.owner_id is distinct from prior_owner/);assert.match(sql,/checkin_owner_eligibility/);assert.match(sql,/checkin_applicant_archival/);assert.match(sql,/read_at=null,created_at=clock_timestamp/);assert.match(sql,/alter column actor_id drop not null/);assert.match(sql,/to service_role/);assert.doesNotMatch(sql,/grant .* to authenticated/);});
