const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const api=require('../operations/private-pdf-viewer.js');
const sample=require('./helpers/sample-resume-pdf.cjs');
const origin='https://project.supabase.co',url=origin+'/storage/v1/object/sign/soro-private-documents/test.pdf?token=private';
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function defer(){let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};}
function hostFixture(){
  const elements=new Map(),listeners={};
  for(const name of ['status','pages','prev','next','page','zoom','text','text-details'])elements.set(name,{textContent:'',hidden:false,disabled:false,children:[],clientWidth:620,replaceChildren(){this.children=[];},append(node){this.children.push(node);},querySelectorAll(){return this.children;}});
  const host={isConnected:true,ownerDocument:{createElement(){return{style:{},setAttribute(){},getContext(){return{};}};}},querySelector(selector){return elements.get(selector.slice(10,-1));},addEventListener(name,fn){listeners[name]=fn;},removeEventListener(name){delete listeners[name];}};
  return{host,elements,listeners};
}
function harness(overrides={}){
  const h=hostFixture(),calls={fetch:[],render:[],destroy:0,cancel:0,options:null},doc={numPages:2,async getPage(number){if(overrides.page)await overrides.page.promise;return{getViewport:({scale})=>({width:612*scale,height:792*scale}),render(options){calls.render.push({number,...options});return{promise:overrides.render?.promise||Promise.resolve(),cancel(){calls.cancel++;}};},getTextContent:async()=>({items:[{str:'Sample page '+number,hasEOL:true}]}),cleanup(){}};}};
  let current=true;
  const viewer=api.mount(h.host,{url,storageOrigin:origin,isCurrent:()=>current},{fetch:async(...args)=>{calls.fetch.push(args);if(overrides.fetch)await overrides.fetch.promise;return new Response(sample());},loadLibrary:async()=>{if(overrides.library)await overrides.library.promise;return{getDocument(options){calls.options=options;return{promise:overrides.document?.promise||Promise.resolve(doc),destroy(){calls.destroy++;return Promise.resolve();}};}};}});
  return{...h,calls,viewer,doc,invalidate:()=>current=false};
}
test('private URL allowlist rejects arbitrary origins, protocols, paths and credentials',()=>{assert.equal(api.validateUrl(url,origin),url);for(const bad of ['http://project.supabase.co/storage/v1/object/sign/soro-private-documents/a','https://evil.example/a',origin+'/other','https://user:pass@project.supabase.co/storage/v1/object/sign/soro-private-documents/a'])assert.throws(()=>api.validateUrl(bad,origin));});
test('PDF bytes are bounded and signature-checked, including chunked responses',async()=>{const signal=new AbortController().signal;assert.deepEqual(await api.readPdf(new Response(sample()),signal),new Uint8Array(sample()));await assert.rejects(api.readPdf(new Response('<html>not a PDF</html>'),signal));await assert.rejects(api.readPdf(new Response('%PDF-',{headers:{'content-length':String(api.MAX_BYTES+1)}}),signal));let cancelled=false;const stream=new ReadableStream({start(c){c.enqueue(new Uint8Array(api.MAX_BYTES));c.enqueue(new Uint8Array(1));},cancel(){cancelled=true;}});await assert.rejects(api.readPdf(new Response(stream),signal));assert.equal(cancelled,true);});
test('renders page one with private no-cache fetch, disabled active content and navigation',async()=>{const h=harness();await h.viewer.ready;assert.equal(h.elements.get('page').textContent,'Page 1 of 2');assert.equal(h.elements.get('prev').disabled,true);assert.equal(h.elements.get('next').disabled,false);assert.equal(h.calls.fetch[0][1].credentials,'omit');assert.equal(h.calls.fetch[0][1].cache,'no-store');assert.equal(h.calls.fetch[0][1].redirect,'error');assert.equal(h.calls.fetch[0][1].referrerPolicy,'no-referrer');assert.equal(h.calls.options.url,undefined);assert.equal(h.calls.options.enableXfa,false);assert.equal(h.calls.options.isEvalSupported,false);h.listeners.click({target:{closest:()=>({disabled:false,hasAttribute:()=>true})},preventDefault(){}});await tick();assert.equal(h.elements.get('page').textContent,'Page 2 of 2');h.viewer.destroy();assert.equal(h.calls.destroy,1);assert.equal(h.elements.get('pages').children.length,0);});
for(const stage of ['fetch','library','document','page','render'])test('closing during '+stage+' prevents stale PDF content',async()=>{const wait=defer(),h=harness({[stage]:wait});await tick();h.viewer.destroy();wait.resolve(h.doc);await h.viewer.ready;assert.equal(h.elements.get('pages').children.length,0);assert.equal(h.elements.get('text').textContent,'');assert.equal(h.calls.fetch[0][1].signal.aborted,true);});
test('access change during import cannot create a PDF document',async()=>{const gate=defer(),h=harness({library:gate});await tick();h.invalidate();gate.resolve();await h.viewer.ready;assert.equal(h.calls.options,null);h.viewer.destroy();});
test('overlapping reload cleanup cannot clear a newer viewer',async()=>{const gate=defer(),old=harness({render:gate});await tick();old.viewer.destroy();const fresh=harness();await fresh.viewer.ready;gate.resolve();await old.viewer.ready;assert.equal(fresh.elements.get('page').textContent,'Page 1 of 2');assert.equal(fresh.calls.destroy,0);fresh.viewer.destroy();});
test('pixel allocation is bounded even for unusual page geometry',()=>{const d=api.dimensions(15000,19000,800,2,3);assert.ok(15000*19000*d.scale*d.scale*d.density*d.density<=8000001);assert.throws(()=>api.dimensions(0,100,500,1,1));});
test('the queue preserves a mounted PDF on reference updates and destroys it on idle exit/reload',()=>{const source=fs.readFileSync(require.resolve('../operations/talent-review-queue.js'),'utf8');assert.match(source,/stopResumeViewer\(\);\s*mountedRoot.innerHTML = pageMarkup/);assert.match(source,/function closeVerification\(\) \{\s*if \(pendingVerificationAction\) return false;\s*stopResumeViewer/);assert.match(source,/if \(kind === 'resume'\) stopResumeViewer/);assert.match(source,/evidence.resume === state/);assert.match(source,/root.soroSupabase === client/);});
