'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ui=require('../operations/work-log'),api=require('../netlify/functions/work-log')._test;
const id=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0'),source=fs.readFileSync('operations/work-log.js','utf8'),flush=()=>new Promise(r=>setImmediate(r));
function seed(){return {viewerRole:'client_admin',generatedAt:'2026-09-09T06:00:00Z',from:'2026-08-10',to:'2026-09-09',placements:[{id:id(1),talentName:'Sample Talent',clientName:'Sample Client',status:'active',canRequest:true,canShare:false}],sessions:[{id:id(2),placementId:id(1),workDate:'2026-09-09',timezone:'Asia/Manila',startedAt:'2026-09-09T01:00:00Z',checkedOutAt:'2026-09-09T05:30:00Z',corrected:false}],requests:[],images:[],offset:0,total:1};}
test('Work Log validates real data and dates, rejecting mismatched relationships',()=>{assert.ok(ui.validate(seed()));for(const bad of [null,{...seed(),viewerRole:'sales'},{...seed(),total:-1},{...seed(),sessions:[{...seed().sessions[0],placementId:id(9)}]},{...seed(),sessions:[{...seed().sessions[0],workDate:'2026-02-30'}]}])assert.throws(()=>ui.validate(bad));assert.equal(ui.day('9999-99-99'),false);assert.equal(ui.day('2024-02-29'),true);});
test('Work time remains elapsed, not payroll, and long open sessions are flagged',()=>{const s=seed().sessions[0];assert.equal(ui.duration(s,seed().generatedAt),'4h 30m');assert.equal(ui.stale({...s,checkedOutAt:null},'2026-09-10T01:00:00Z'),true);const html=ui.markup(seed());assert.match(html,/Completed time · this page/);assert.match(html,/not sign-in activity|not sign-in|not.*sign-in|entries—not sign-in/);assert.match(html,/payroll hours/);});
test('Client and Talent controls differ; ended screenshot remains withdrawable',()=>{const v=seed();assert.match(ui.markup(v),/data-wl="request"/);assert.doesNotMatch(ui.markup(v),/data-wl="share"/);v.viewerRole='client_reviewer';v.placements[0].canRequest=false;assert.doesNotMatch(ui.markup(v),/data-wl="request"/);v.viewerRole='virtual_assistant';v.placements[0].status='ended';v.images=[{id:id(3),placementId:id(1),sessionId:id(2),sharedAt:'2026-09-09T06:00:00Z',note:'Example'}];assert.match(ui.markup(v),/data-wl="withdraw"/);assert.doesNotMatch(ui.markup(v),/data-wl="share"/);});
test('Names and shared notes cannot inject markup',()=>{const v=seed();v.placements[0].talentName='<img src=x>';v.requests=[{id:id(3),placementId:id(1),workDate:'2026-09-09',createdAt:'2026-09-09T02:00:00Z',status:'requested',note:'<script>bad</script>'}];const html=ui.markup(v);assert.doesNotMatch(html,/<script>|<img src=x>/);assert.match(html,/&lt;script&gt;/);});
test('API accepts only bounded dates, exact action fields and IDs',()=>{for(const v of [{role:'admin'},{clientId:id(1)},{from:'2026-02-29'},{offset:'-1'},{offset:'999999'},{imageId:id(1),from:'2026-01-01'},{placementId:'all'}])assert.throws(()=>api.query(v));assert.ok(api.query({from:'2024-02-29'}));const b={action:'request',requestId:id(3),placementId:id(1),workDate:'2026-09-09',note:''};assert.equal(api.body({body:JSON.stringify(b)}).action,'request');for(const bad of [{...b,actor:id(9)},{...b,action:'finalize'},{...b,workDate:'2026-09-31'},{...b,note:'x'.repeat(501)}])assert.throws(()=>api.body({body:JSON.stringify(bad)}));});
test('Images require real allowed signatures, size and bounded dimensions',()=>{const b=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(b);b.write('IHDR',12);b.writeUInt32BE(1200,16);b.writeUInt32BE(800,20);const body={action:'share',requestId:id(3),sessionId:id(2),note:'',image:{type:'image/png',dataBase64:b.toString('base64')}};assert.equal(api.body({body:JSON.stringify(body)}).image.bytes.length,24);for(const image of [null,{type:'image/svg+xml',dataBase64:Buffer.from('<svg/>').toString('base64')},{type:'image/jpeg',dataBase64:b.toString('base64')},{type:'image/png',dataBase64:'not base64'}])assert.throws(()=>api.body({body:JSON.stringify({...body,image})}));b.writeUInt32BE(20000,16);assert.throws(()=>api.body({body:JSON.stringify({...body,image:{type:'image/png',dataBase64:b.toString('base64')}})}));});
test('Storage references and signed links are exact-origin and dedicated-bucket',()=>{const prior={...process.env};process.env.SUPABASE_URL='https://test.supabase.co';process.env.SUPABASE_SERVICE_ROLE_KEY='TEST_ONLY';try{const p=[id(1),id(2),id(3),id(4),'a'.repeat(64)+'.png'].join('/');assert.equal(api.path(p),'soro-work-evidence/'+p);assert.throws(()=>api.path('../other.png'));assert.match(api.signedURL('/object/sign/soro-work-evidence/'+p+'?token=example'),/^https:\/\/test.supabase.co/);for(const v of ['https://evil.supabase.co/storage/v1/object/sign/soro-work-evidence/a','/object/sign/other/a','https://test.supabase.co.evil.test/storage/v1/object/sign/soro-work-evidence/a'])assert.throws(()=>api.signedURL(v));}finally{process.env.SUPABASE_URL=prior.SUPABASE_URL||'';process.env.SUPABASE_SERVICE_ROLE_KEY=prior.SUPABASE_SERVICE_ROLE_KEY||'';}});
function boot(overrides={}){const host={isConnected:true,innerHTML:'',setAttribute(){},removeAttribute(){},replaceChildren(){this.innerHTML='';}},c={module:{exports:{}},AbortController,URL,URLSearchParams,Intl,Date,FormData,console,addEventListener(){},soroCurrentAccess:{user_id:id(13),organization_id:id(1),role:'client_admin',active:true,must_change_password:false},soroSupabase:{auth:{getSession:async()=>({data:{session:{user:{id:id(13)},access_token:'TEST_ONLY'}}})}},fetch:async()=>({ok:true,json:async()=>seed()}),...overrides};vm.runInNewContext(source,c);return {ui:c.module.exports,c,host};}
test('Real user_id auth shape reaches the endpoint with bearer and displays dates',async()=>{let call;const b=boot({fetch:async(url,opts)=>{call={url,opts};return {ok:true,json:async()=>seed()};}});b.ui.mount(b.host);await flush();assert.equal(call.url,'/.netlify/functions/work-log');assert.equal(call.opts.headers.Authorization,'Bearer TEST_ONLY');assert.match(b.host.innerHTML,/Sample Talent/);assert.match(b.host.innerHTML,/value="2026-08-10"/);});
test('Another-role previews and wrong sessions never query live work logs',async()=>{for(const change of ['preview','rolepreview','wronguser','password']){let calls=0;const b=boot({fetch:async()=>{calls++;return {ok:true,json:async()=>seed()};}});if(change==='rolepreview')b.c.adminPreviewingNonAdminWorkspace=()=>true;if(change==='wronguser')b.c.soroCurrentAccess.user_id=id(99);if(change==='password')b.c.soroCurrentAccess.must_change_password=true;b.ui.mount(b.host,{preview:change==='preview'});await flush();assert.equal(calls,0,change);}});
test('Deferred token acquisition cannot send a request after remount',async()=>{let release,calls=0;const b=boot({fetch:async()=>{calls++;return {ok:true,json:async()=>seed()};},soroSupabase:{auth:{getSession:()=>new Promise(r=>release=r)}}});b.ui.mount(b.host);b.ui.unmount();release({data:{session:{user:{id:id(13)},access_token:'TEST'}}});await flush();assert.equal(calls,0);});
test('Late replies cannot cross account/org/controller/role/navigation boundaries',async()=>{for(const key of ['user','org','client','role','unmount','detach']){let release;const b=boot({fetch:()=>new Promise(r=>release=r)});b.ui.mount(b.host);await flush();if(key==='user')b.c.soroCurrentAccess.user_id=id(99);if(key==='org')b.c.soroCurrentAccess.organization_id=id(99);if(key==='client')b.c.soroSupabase={};if(key==='role')b.c.soroCurrentAccess.role='client_billing';if(key==='unmount')b.ui.unmount();if(key==='detach')b.host.isConnected=false;release({ok:true,json:async()=>seed()});await flush();assert.doesNotMatch(b.host.innerHTML,/Sample Talent/,key);}});
test('Work Log integrates with the dashboard and menus without moving Start Day',()=>{const op=fs.readFileSync('operations/operations.js','utf8'),home=fs.readFileSync('operations/client-dashboard.js','utf8');assert.match(op,/\['admin','talent_management','client_admin','client_reviewer','virtual_assistant'\].*add\('work-log'\)/);assert.match(op,/current==='work-log'/);assert.match(home,/actionButton\('work-log',row.placementId/);assert.match(home,/workspace.talent.some\(row=>row.placementId===id\)/);assert.match(op,/Work Log & screenshots/);assert.doesNotMatch(source,/start_day|check_out|start_request_id/);});
test('Escape during a save releases only that operation; old responses cannot clear a newer save',async()=>{
 for(const failOld of [false,true]){
  const b=boot(),pending=[];
  vm.runInNewContext(source.replace('return Object.freeze({mount,','root.__wlTest={mutate,closeDialog,setDialog:d=>dialog=d,isBusy:()=>busy};return Object.freeze({mount,'),b.c);
  const adapter=async(method)=>method==='GET'?seed():new Promise((resolve,reject)=>pending.push({resolve,reject}));
  b.c.module.exports.mount(b.host,{adapter,role:'client_admin'});await flush();
  const dialog=()=>({isConnected:true,close(){},remove(){this.isConnected=false;},querySelectorAll:()=>[],querySelector:()=>({textContent:''})});
  const first=dialog();b.c.__wlTest.setDialog(first);const oldSave=b.c.__wlTest.mutate({},first);await flush();assert.equal(b.c.__wlTest.isBusy(),true);b.c.__wlTest.closeDialog();assert.equal(b.c.__wlTest.isBusy(),false);
  const second=dialog();b.c.__wlTest.setDialog(second);const newSave=b.c.__wlTest.mutate({},second);await flush();assert.equal(b.c.__wlTest.isBusy(),true);
  if(failOld)pending[0].reject(new Error('Old failure'));else pending[0].resolve({id:id(1)});await oldSave;assert.equal(b.c.__wlTest.isBusy(),true);assert.equal(second.isConnected,true);
  pending[1].resolve({id:id(2)});await newSave;assert.equal(b.c.__wlTest.isBusy(),false);assert.equal(second.isConnected,false);
 }
});
