(function(root){
  'use strict';
  const ENDPOINT='/.netlify/functions/document-center';
  const TYPES={print_sign:'Print, sign & upload',upload:'Upload a document',acknowledge:'Read & acknowledge',form:'Complete a form'};
  const TEAMS={talent_management:'Talent Management',sales:'Sales',admin:'Administration',billing:'Billing'};
  const STATES={pending:'To do',submitted:'Needs review',returned:'Corrections requested',accepted:'Accepted',complete:'Complete',cancelled:'Cancelled'};
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>v?new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No due date';
  let host,options={},generation=0,viewSequence=0,notificationSequence=0,workspace=null,selected=null,actorId='',tab='mine',query='',status='',offset=0;
  const controllers=new Set();
  const context=()=>({generation,actorId,host,options});
  function guard(c){if(c.generation!==generation||c.host!==host||c.actorId!==actorId||(!c.options.preview&&root.soroCurrentAccess?.user_id!==c.actorId))throw Error('This view or account changed. Open Documents again.');}
  const subjectFilters=()=>options.subjectKind&&options.subjectId?{subjectKind:options.subjectKind,subjectId:options.subjectId}:{};
  function badge(s){return `<span class="dc-status dc-status--${escape(s)}">${escape(STATES[s]||s)}</span>`;}
  function empty(title,body){return `<div class="dc-empty"><span aria-hidden="true">◇</span><h2>${title}</h2><p>${body}</p></div>`;}
  function shell(){return `<main class="page dc-page"><header class="page-heading"><div><p class="eyebrow">Soro Operations</p><h1>Document Center</h1><p class="dc-subtitle">The right forms. One place to follow through.</p></div><div class="heading-actions"><button type="button" class="button" data-dc-refresh>Refresh</button></div></header><p class="dc-feedback" role="status" aria-live="polite" data-dc-feedback></p><div data-dc-content>${empty('Loading your documents','Checking the files and requests available to your account.')}</div></main>`;}
  async function api(method='GET',body=null,search='',c=context()){
    guard(c);if(c.options.preview&&method!=='GET')throw Error('Saving is disabled in this layout review.');
    if(c.options.request){const result=await c.options.request(method,body,search);guard(c);return result;}
    const session=(await root.soroSupabase?.auth.getSession())?.data?.session;guard(c);
    if(!session?.access_token||session.user.id!==c.actorId)throw Error('Your account changed. Sign in again.');
    const controller=new AbortController();controllers.add(controller);
    try{
      const res=await root.fetch(ENDPOINT+search,{method,headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},cache:'no-store',...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(55000)])});
      const value=await res.json();guard(c);if(!res.ok)throw Error(value.message||'The document action could not be completed.');return value;
    }finally{controllers.delete(controller);}
  }
  const feedback=message=>{const n=host?.querySelector('[data-dc-feedback]');if(n)n.textContent=message;};
  function navMarkup(){return `<nav class="dc-tabs" aria-label="Document views">${[['mine','My Documents'],...(workspace.internal?[['team','Team Requests'],['library','Forms & Packets'],...(workspace.canManageTemplates?[['captured','Captured Files']]:[])]:[])].map(([id,label])=>`<button type="button" data-dc-tab="${id}" aria-current="${tab===id?'page':'false'}">${label}</button>`).join('')}</nav>`;}
  function filesMarkup(files){return files.length?`<div class="dc-file-list">${files.map(f=>`<article class="dc-file"><div><strong>${escape(f.name)}</strong><span>${escape(f.category||'Document')} · ${escape(f.subjectName||'Personal document')} · ${escape(date(f.createdAt))}</span></div>${f.canOpen===false?'<span class="dc-kicker">External source · not imported</span>':`<button type="button" class="button" data-dc-file="${escape(f.id)}" data-dc-origin="${escape(f.origin||'center')}">Open securely ↗</button>`}${f.canClassify?`<button type="button" class="button" data-dc-classify="${escape(f.id)}">${f.reviewedShare?'Edit sharing':'Classify & share'}</button>${f.reviewedShare?`<button type="button" class="text-button" data-dc-unshare="${escape(f.id)}">Remove reviewed share</button>`:''}`:''}</article>`).join('')}</div>`:empty('No completed documents here yet','Your existing accessible uploads and completed packet documents will appear here.');}
  function requestsMarkup(records){return records.length?`<div class="dc-request-list">${records.map(r=>`<button type="button" class="dc-request" data-dc-request="${escape(r.id)}"><span class="dc-request-main"><span class="dc-kicker">${escape(TEAMS[r.team]||'Documents')} · ${escape(r.subjectName)}</span><strong>${escape(r.title)}</strong><span>${r.completedCount} of ${r.itemCount} items accepted · ${escape(r.recipientName||'Recipient')}</span></span><span class="dc-request-end">${badge(r.status)}<span>${r.dueDate?'Due '+escape(date(r.dueDate)):'No due date'}</span><span aria-hidden="true">→</span></span></button>`).join('')}</div>`:empty(tab==='team'?'No document requests yet':'You’re up to date',tab==='team'?'Assign an approved packet to start a document request.':'When Soro requests a document from you, it will appear here.');}
  function libraryMarkup(){return `<div class="dc-section-head"><div><h2>Approved forms & packets</h2><p>Reusable originals stay separate from completed personal documents.</p></div>${workspace.canManageTemplates?'<button class="button primary" type="button" data-dc-create="template">Add form</button><button class="button" type="button" data-dc-create="packet">Create packet</button>':''}</div><h3 class="dc-list-label">Packets</h3>${workspace.packets?.length?`<div class="dc-library-grid">${workspace.packets.map(p=>`<article class="dc-library-card"><span class="dc-kicker">${escape(TEAMS[p.team])}</span><h3>${escape(p.title)}</h3><p>${escape(p.description||'A reusable group of approved forms.')}</p><div class="dc-card-footer"><span>${p.templateIds.length} forms · ${escape(p.audience)}</span><button class="button" type="button" data-dc-assign="${escape(p.id)}">Assign packet</button>${workspace.canManageTemplates?`<button class="text-button" type="button" data-dc-archive-packet="${escape(p.id)}">Retire</button>`:''}</div></article>`).join('')}</div>`:empty('No approved packets yet','An administrator can group approved forms into a Talent, Client, or Employee packet.')}<h3 class="dc-list-label">Forms</h3>${workspace.templates?.length?`<div class="dc-file-list">${workspace.templates.map(t=>`<article class="dc-file"><div><strong>${escape(t.title)}</strong><span>${escape(TEAMS[t.team])} · ${escape(TYPES[t.kind])} · ${escape(t.category)}</span></div>${t.fileId?`<button class="button" type="button" data-dc-file="${escape(t.fileId)}">View original</button>`:''}${workspace.canManageTemplates?`<button class="text-button" type="button" data-dc-archive-template="${escape(t.id)}">Retire</button>`:''}</article>`).join('')}</div>`:empty('No forms have been published','Only approved originals belong in this library. Existing signed or personal documents are not converted into templates.')}`;}
  function render(){
    if(!host||!workspace)return;
    const content=host.querySelector('[data-dc-content]');
    content.innerHTML=`${options.preview?'<div class="dc-notice">Local layout review · no sample accounts or documents. Saving is disabled until connected to the document service.</div>':''}${navMarkup()}${tab==='library'?libraryMarkup():tab==='captured'?`<div class="dc-section-head"><div><h2>Captured files</h2><p>Admin-only inventory. Existing Talent links stay intact; unclassified files are not shared automatically.</p></div></div>${filesMarkup(workspace.files||[])}${workspace.filesHasMore?'<button class="button" type="button" data-dc-more-files>Load more documents</button>':''}`:`<div class="dc-section-head"><div><h2>${options.subjectId?'Profile documents & requests':tab==='mine'?'Your documents & requests':'Team document requests'}</h2><p>${tab==='mine'?'Your personal records, separate from the work you manage for others.':'Follow submissions, review corrections, and keep onboarding moving.'}</p></div>${tab==='team'?'<button class="button primary" type="button" data-dc-create="assign">Assign packet</button>':''}</div><form class="dc-filters" data-dc-search><label>Search<input name="q" type="search" value="${escape(query)}" placeholder="Document, packet, or person" maxlength="100"></label><label>Request status<select name="status"><option value="">All statuses</option>${Object.entries(STATES).filter(([s])=>s!=='accepted').map(([s,l])=>`<option value="${s}" ${status===s?'selected':''}>${l}</option>`).join('')}</select></label><button class="button" type="submit">Apply</button></form>${requestsMarkup(workspace.requests||[])}<div class="dc-pagination"><span>${workspace.total||0} requests</span><button class="button" data-dc-page="-1" ${offset===0?'disabled':''}>Previous</button><button class="button" data-dc-page="1" ${workspace.hasMore?'':'disabled'}>Next</button></div>${tab==='mine'||options.subjectId?`<div class="dc-section-head"><div><h2>Saved documents</h2><p>Your existing uploads and submission versions, linked to the same personal record.</p></div></div>${filesMarkup(workspace.files||[])}${workspace.filesHasMore?'<button class="button" type="button" data-dc-more-files>Load more documents</button>':''}`:''}`}`;
  }
  async function load(){const c=context(),seq=++viewSequence;selected=null;try{const data=await api('GET',null,'?'+new URLSearchParams({view:tab,q:query,status,offset,...subjectFilters()}),c);guard(c);if(seq!==viewSequence)return;workspace=options.personalOnly?{...data,internal:false,canManageTemplates:false,packets:[],templates:[]}:data;if(!workspace.internal&&tab!=='mine'){tab='mine';return load();}render();}catch(e){if(c.generation===generation&&seq===viewSequence&&host){host.querySelector('[data-dc-content]').innerHTML=empty('Documents could not be loaded','Your files have not been changed. Use Refresh to try again.');feedback(e.message);}}}
  function fieldsMarkup(fields,answers={},disabled=false){return(fields||[]).map(f=>`<label>${escape(f.label)}${f.required?'':' (optional)'}<input name="field_${escape(f.id)}" value="${escape(answers[f.id]||'')}" maxlength="2000" ${f.required?'required':''} ${disabled?'readonly':''}></label>`).join('');}
  function itemMarkup(i,request){
    const canSubmit=request.canSubmit&&['pending','returned'].includes(i.status),canReview=request.canReview&&i.canReview===true&&i.status==='submitted';
    return `<article class="dc-item"><div class="dc-section-head"><div><span class="dc-kicker">${escape(TYPES[i.kind])}</span><h3>${escape(i.title)}</h3></div>${badge(i.status)}</div>${i.instructions?`<p class="dc-instructions">${escape(i.instructions)}</p>`:''}${i.kind==='print_sign'?'<p class="dc-notice">Download the original, complete it, sign and date it by hand, then upload a clear copy of every page. Uploading sends it for review; it is not an electronic signature.</p>':''}${i.sourceFileId?`<button class="button" type="button" data-dc-file="${escape(i.sourceFileId)}">Download original ↗</button>`:''}${i.latestFileId?`<button class="button" type="button" data-dc-file="${escape(i.latestFileId)}">View latest submission ↗</button>`:''}${i.correction?`<p class="dc-correction"><strong>Corrections requested:</strong> ${escape(i.correction)}</p>`:''}${canSubmit?`<form class="dc-form dc-submit" data-dc-submit="${escape(i.id)}">${['upload','print_sign'].includes(i.kind)?'<label>Completed document<input type="file" name="file" accept="application/pdf,image/png,image/jpeg,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required></label><small>PDF, PNG, JPG, or DOCX · up to 10 MB. Previous submissions are preserved.</small>':i.kind==='form'?fieldsMarkup(i.fields,i.answers):'<label class="dc-check"><input type="checkbox" name="acknowledge" required> I have read and acknowledge this document.</label>'}<button class="button primary" type="submit">${i.kind==='acknowledge'?'Submit acknowledgment':'Submit for review'}</button></form>`:i.kind==='form'&&!i.restricted?`<div class="dc-form">${fieldsMarkup(i.fields,i.answers,true)}</div>`:''}${canReview?`<form class="dc-form" data-dc-review="${escape(i.id)}"><label>Review outcome<select name="decision"><option value="accepted">Accept submission</option><option value="returned">Return for correction</option></select></label><label>Note to recipient (required for corrections)<textarea name="note" maxlength="2000"></textarea></label><button class="button" type="submit">Save review</button></form>`:''}${i.versions?.length?`<details class="dc-versions"><summary>Submission history (${i.versions.length})</summary>${i.versions.map(v=>`<div><span>Version ${v.version} · ${escape(date(v.createdAt))}</span>${v.fileId?`<button class="text-button" type="button" data-dc-file="${escape(v.fileId)}">Open</button>`:''}</div>`).join('')}</details>`:''}</article>`;
  }
  async function openRequest(id){const c=context(),seq=++viewSequence;try{const r=await api('GET',null,'?requestId='+encodeURIComponent(id),c);guard(c);if(seq!==viewSequence)return;selected=r;host.querySelector('[data-dc-content]').innerHTML=`<button class="button" type="button" data-dc-back>← Back to documents</button><header class="dc-detail-heading"><div><p class="dc-kicker">${escape(TEAMS[r.team])} · ${escape(r.subjectName)}</p><h2>${escape(r.title)}</h2><p>${escape(r.recipientName)} · ${r.dueDate?'Due '+escape(date(r.dueDate)):'No due date'}</p></div>${badge(r.status)}</header>${r.canCancel?'<button type="button" class="text-button" data-dc-cancel>Cancel request</button>':''}<div class="dc-detail-layout"><section aria-label="Packet documents">${r.items.map(i=>itemMarkup(i,r)).join('')}</section><aside class="dc-activity"><h3>Activity</h3><p>Recorded changes for this request.</p>${(r.activity||[]).map(e=>`<article><strong>${escape(e.action)}</strong><span>${escape(e.actorName||'Soro')} · ${escape(date(e.createdAt))}</span>${e.note?`<p>${escape(e.note)}</p>`:''}</article>`).join('')||'<p>No recorded activity yet.</p>'}</aside></div>`;}catch(e){if(c.generation===generation)feedback(e.message);}}
  function dialog(title,markup,onSubmit){const c=context();guard(c);const d=root.document.createElement('dialog');d.className='dc-dialog';d.innerHTML=`<form class="dc-form"><div class="dc-section-head"><h2>${title}</h2><button type="button" class="button" data-close aria-label="Close dialog">×</button></div>${markup}<p role="status" data-dialog-error></p><div class="dc-dialog-footer"><button type="button" class="button" data-close>Cancel</button><button class="button primary" type="submit" ${options.preview?'disabled':''}>Save</button></div></form>`;host.append(d);d.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>d.close());d.onclose=()=>d.remove();d.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{guard(c);await onSubmit(new FormData(e.target),c);guard(c);d.close();await load();guard(c);feedback('Saved.');refreshNotifications();}catch(error){if(c.generation===generation){d.querySelector('[data-dialog-error]').textContent=error.message;b.disabled=false;}}};d.showModal();}
  async function upload(file,purpose,itemId=null,c=context()){
    guard(c);
    if(!file?.size||file.size>10*1024*1024)throw Error('Choose a document up to 10 MB.');
    const started=await api('POST',{action:'prepare_upload',requestId:root.crypto.randomUUID(),purpose,itemId,name:file.name,type:file.type,size:file.size},'',c);
    const controller=new AbortController();controllers.add(controller);let response;
    try{response=await root.fetch(started.url,{method:'PUT',headers:{'Content-Type':file.type,'x-upsert':'false'},body:file,signal:AbortSignal.any([controller.signal,AbortSignal.timeout(120000)])});}finally{controllers.delete(controller);}
    guard(c);if(!response.ok)throw Error('The upload did not finish. Choose the file again to retry.');
    const finished=await api('POST',{action:'complete_upload',fileId:started.fileId},'',c);guard(c);return finished.fileId;
  }
  function createTemplate(){dialog('Add an approved form',`<label>Form title<input name="title" required maxlength="160"></label><div class="dc-form-row"><label>Team<select name="team">${Object.entries(TEAMS).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>For<select name="audience"><option value="talent">Talent</option><option value="client">Clients</option><option value="employee">Employees</option></select></label></div><label>Category<select name="category"><option value="onboarding">Onboarding</option><option value="agreement">Agreement</option><option value="tax">Tax document — restricted</option><option value="policy">Policy</option><option value="evidence">Supporting evidence</option><option value="business">Client business</option></select></label><label>Recipient action<select name="kind">${Object.entries(TYPES).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Instructions<textarea name="instructions" maxlength="4000"></textarea></label><label>Approved original (required for print/sign and acknowledgment)<input type="file" name="file" accept=".pdf,.docx,.png,.jpg,.jpeg"></label><label>For online information forms: question labels, one per line<textarea name="questions" maxlength="3000" placeholder="Do not use online forms for tax certifications or signatures."></textarea></label><label class="dc-check"><input type="checkbox" required> This is an approved reusable original, not a completed personal document.</label>`,async (f,c)=>{
      let fileId=null;if(f.get('file')?.size)fileId=await upload(f.get('file'),'template',null,c);guard(c);
      const fields=String(f.get('questions')||'').split('\n').map(x=>x.trim()).filter(Boolean).map((label,i)=>({id:'q'+(i+1),label,required:false}));
      return api('POST',{action:'create_template',requestId:root.crypto.randomUUID(),title:f.get('title'),team:f.get('team'),audience:f.get('audience'),category:f.get('category'),kind:f.get('kind'),instructions:f.get('instructions'),fields,fileId},'',c);
    });}
  function createPacket(){dialog('Create an onboarding packet',`<label>Packet title<input name="title" required maxlength="160"></label><label>Description<textarea name="description" maxlength="2000"></textarea></label><fieldset><legend>Approved forms</legend>${workspace.templates?.length?workspace.templates.map(t=>`<label class="dc-check"><input type="checkbox" name="templateIds" value="${escape(t.id)}"> ${escape(t.title)} · ${escape(TEAMS[t.team])} · ${escape(t.audience)}</label>`).join(''):'<p>Add approved forms first.</p>'}</fieldset><p class="dc-notice">Choose forms for the same team and recipient type. Existing assignments keep the original versions when a template is retired.</p>`,(f,c)=>api('POST',{action:'create_packet',requestId:root.crypto.randomUUID(),title:f.get('title'),description:f.get('description'),templateIds:f.getAll('templateIds')},'',c));}
  async function assignPacket(packetId=''){
    const c=context();try{const data=options.preview?{recipients:[]}:await api('GET',null,'?recipients=1',c);guard(c);dialog('Assign a packet',`<label>Packet<select name="packetId" required><option value="">Choose an approved packet</option>${(workspace.packets||[]).map(p=>`<option value="${escape(p.id)}" ${packetId===p.id?'selected':''}>${escape(p.title)} · ${escape(p.audience)}</option>`).join('')}</select></label><label>Recipient<select name="recipient" required><option value="">Choose a person with portal access</option>${data.recipients.map(r=>`<option value="${escape(r.kind+':'+r.subjectId+':'+r.userId)}">${escape(r.name)} · ${escape(r.kind)}</option>`).join('')}</select></label><label>Due date (optional)<input type="date" name="dueDate"></label><p class="dc-notice">The recipient gets a portal notification. Tax submissions are restricted to the recipient and Admin/Billing; Talent Management can follow completion without reading the tax file.</p>`,f=>{const[kind,subjectId,userId]=String(f.get('recipient')).split(':');return api('POST',{action:'assign',requestId:root.crypto.randomUUID(),packetId:f.get('packetId'),subjectKind:kind,subjectId,recipientId:userId,dueDate:f.get('dueDate')||null},'',c);});}catch(e){feedback(e.message);}
  }
  async function click(e){
    const b=e.target.closest('button');if(!b||!host?.contains(b))return;const c=context();
    try{
      if(b.hasAttribute('data-dc-refresh')||b.hasAttribute('data-dc-back'))return load();
      if(b.dataset.dcTab){tab=b.dataset.dcTab;if(tab==='mine'){options={...options,subjectKind:null,subjectId:null};if(!options.preview)root.history?.replaceState({},'',root.location.pathname+'#documents');}offset=0;status='';return load();}
      if(b.dataset.dcPage){offset=Math.max(0,offset+Number(b.dataset.dcPage)*30);return load();}
      if(b.dataset.dcRequest)return openRequest(b.dataset.dcRequest);
      if(b.dataset.dcFile){const popup=root.open('about:blank','_blank');if(popup)popup.opener=null;try{const x=await api('GET',null,'?'+new URLSearchParams({fileId:b.dataset.dcFile,origin:b.dataset.dcOrigin||'center'}),c);guard(c);if(!popup)throw Error('Allow pop-ups to open this private file.');popup.location.replace(x.url);}catch(error){popup?.close();throw error;}return;}
      if(b.dataset.dcClassify)return classifyLegacy(b.dataset.dcClassify);
      if(b.dataset.dcUnshare){if(!root.confirm('Remove this reviewed share? The original file and its existing profile permissions remain unchanged.'))return;await api('POST',{action:'unlink_legacy',requestId:root.crypto.randomUUID(),id:b.dataset.dcUnshare},'',c);guard(c);return load();}
      if(b.dataset.dcCreate==='template')return createTemplate();
      if(b.dataset.dcCreate==='packet')return createPacket();
      if(b.dataset.dcCreate==='assign'||b.dataset.dcAssign)return assignPacket(b.dataset.dcAssign||'');
      if(b.dataset.dcArchiveTemplate||b.dataset.dcArchivePacket){if(!root.confirm('Retire this original from future assignments? Existing requests and files will be preserved.'))return;await api('POST',{action:'retire',requestId:root.crypto.randomUUID(),kind:b.dataset.dcArchiveTemplate?'template':'packet',id:b.dataset.dcArchiveTemplate||b.dataset.dcArchivePacket},'',c);guard(c);return load();}
      if(b.hasAttribute('data-dc-cancel')){if(!root.confirm('Cancel this request? Existing submissions and history will be preserved.'))return;const id=selected.id;await api('POST',{action:'cancel',requestId:root.crypto.randomUUID(),id,expectedVersion:selected.version},'',c);guard(c);refreshNotifications();return openRequest(id);}
      if(b.hasAttribute('data-dc-more-files')){b.disabled=true;const seq=viewSequence;const more=await api('GET',null,'?'+new URLSearchParams({view:tab,q:query,filesOffset:workspace.files.length,...subjectFilters()}),c);guard(c);if(seq!==viewSequence)return;workspace.files=[...new Map([...workspace.files,...more.files].map(f=>[f.origin+f.id,f])).values()];workspace.filesHasMore=more.filesHasMore;render();}
    }catch(error){if(c.generation===generation)feedback(error.message);}
  }
  async function submit(e){
    const form=e.target;if(form.closest('dialog'))return;
    if(form.hasAttribute('data-dc-search')){e.preventDefault();const f=new FormData(form);query=String(f.get('q'));status=String(f.get('status'));offset=0;return load();}
    if(!form.dataset.dcSubmit&&!form.dataset.dcReview)return;e.preventDefault();const b=e.submitter;b.disabled=true;const request=selected,c=context();try{
      const f=new FormData(form),item=request.items.find(i=>i.id===(form.dataset.dcSubmit||form.dataset.dcReview));
      if(form.dataset.dcReview)await api('POST',{action:'review',requestId:root.crypto.randomUUID(),id:item.id,expectedVersion:request.version,decision:f.get('decision'),note:f.get('note')},'',c);
      else{let fileId=null;if(['upload','print_sign'].includes(item.kind))fileId=await upload(f.get('file'),'submission',item.id,c);guard(c);const answers=Object.fromEntries((item.fields||[]).map(x=>[x.id,String(f.get('field_'+x.id)||'')]));await api('POST',{action:'submit',requestId:root.crypto.randomUUID(),id:item.id,expectedVersion:request.version,fileId,answers,acknowledge:f.get('acknowledge')==='on'},'',c);}
      guard(c);await openRequest(request.id);guard(c);feedback('Saved.');refreshNotifications();
    }catch(error){if(c.generation===generation){feedback(error.message);b.disabled=false;}}
  }
  function mount(node,opts={}){unmount();host=node;options=opts;actorId=root.soroCurrentAccess?.user_id||'';tab=opts.view||(opts.subjectId&&!['virtual_assistant','client_admin','client_reviewer','client_billing'].includes(root.soroCurrentAccess?.role)?'team':'mine');query='';status='';offset=0;host.innerHTML=shell();host.addEventListener('click',click);host.addEventListener('submit',submit);const c=context();load().then(()=>{if(c.generation===generation&&opts.requestId)openRequest(opts.requestId);});}
  function unmount(){generation++;viewSequence++;controllers.forEach(c=>c.abort());controllers.clear();if(host){host.querySelectorAll('dialog').forEach(d=>d.remove());host.removeEventListener('click',click);host.removeEventListener('submit',submit);}host=null;workspace=null;selected=null;}
  function publishNotifications(count){root.soroDocumentNotifications={count};root.dispatchEvent?.(new root.CustomEvent('soro:document-notifications'));}
  async function refreshNotifications(){
    const seq=++notificationSequence,user=root.soroCurrentAccess?.user_id;try{
      const session=(await root.soroSupabase?.auth.getSession())?.data?.session;
      if(!user||!session?.access_token||session.user.id!==user)throw Error('Sign in');
      const res=await root.fetch(ENDPOINT+'?notifications=1',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store',signal:AbortSignal.timeout(12000)});
      const data=await res.json();if(seq!==notificationSequence||user!==root.soroCurrentAccess?.user_id)return;
      publishNotifications(res.ok?Math.max(0,Number(data.count)||0):0);
    }catch{if(seq===notificationSequence)publishNotifications(0);}
  }
  function authChanged(){notificationSequence++;unmount();publishNotifications(0);refreshNotifications();}
  root.addEventListener?.('soro-auth-changed',authChanged);
  async function classifyLegacy(id){
    const c=context();try{const data=await api('GET',null,'?recipients=1',c);guard(c);
      dialog('Classify a captured document',`<p class="dc-notice">Review the original before sharing it. This creates a link to the existing file; it does not move or copy it.</p><label>Personal record<select name="recipient" required><option value="">Choose the correct person</option>${data.recipients.map(r=>`<option value="${escape(r.kind+':'+r.subjectId+':'+r.userId)}">${escape(r.name)} · ${escape(r.kind)}</option>`).join('')}</select></label><label>Category<select name="category"><option value="evidence">Supporting evidence</option><option value="agreement">Agreement</option><option value="tax">Tax document — restricted</option><option value="policy">Policy</option><option value="onboarding">Onboarding</option><option value="business">Business</option></select></label><label class="dc-check"><input type="checkbox" required>I verified that this document belongs to the selected person and may be shared with them.</label>`,(f,c)=>{const [subjectKind,subjectId,recipientId]=String(f.get('recipient')).split(':');return api('POST',{action:'link_legacy',requestId:root.crypto.randomUUID(),id,subjectKind,subjectId,recipientId,category:f.get('category')},'',c);});
    }catch(e){feedback(e.message);}
  }
  root.addEventListener?.('focus',refreshNotifications);
  if(root.document)root.setInterval?.(()=>{if(root.document.visibilityState!=='hidden')refreshNotifications();},60000);
  const exports={mount,unmount,refreshNotifications,escape,filesMarkup,requestsMarkup,fieldsMarkup,TYPES,STATES};
  root.SoroDocumentCenter=exports;if(typeof module==='object')module.exports=exports;
})(typeof window==='undefined'?globalThis:window);
