/* One private pathway, shared by the profile summary and Benefits detail. */
(function(w,f){const api=f(w);if(typeof module==='object'&&module.exports)module.exports=api;if(w?.document)w.SoroDreamPathway=api;})(typeof window==='object'?window:null,function(w){
 'use strict';
 const endpoint='/.netlify/functions/dream-pathway',states={planned:'Planned',in_progress:'In Progress',completed:'Completed',paused:'Paused'};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const day=v=>v?new Date(v+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'No target date';
 const when=v=>v?new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Not scheduled';
 function summary(d){const p=d.plan,m=d.milestones||[],done=m.filter(x=>x.status==='completed').length,next=m.find(x=>!['completed','paused'].includes(x.status));
  if(!p)return`<div class="dp-summary"><p>A practical path starts with a conversation.</p><button type="button" class="button" data-talent-dream-benefits>${d.canManage?'Set Up Dream Pathway':'View Dream Pathway'}</button></div>`;
  return`<div class="dp-summary"><div class="dp-summary-heading"><strong>${esc(p.title)}</strong><span>${done} of ${m.length} milestones reached</span></div><ol class="dp-markers">${m.map((x,i)=>`<li class="dp-${esc(x.status)}"><span aria-label="${esc(states[x.status])}">${x.status==='completed'?'✓':i+1}</span><strong>${esc(x.title)}</strong></li>`).join('')}</ol><div class="dp-next"><p><span>Next Step</span><strong>${esc(next?.title||'Plan Your Next Chapter')}</strong></p><p><span>Quarterly Check-In Due</span><strong>${p.nextReviewOn?day(p.nextReviewOn):'Not set'}</strong></p><button type="button" class="button" data-talent-dream-benefits>View Full Pathway →</button></div></div>`;
 }
 function markup(d){const p=d.plan,m=d.milestones||[],can=d.canManage;
  return`<section class="dp-workspace" aria-label="Dream Pathway"><header class="dp-heading"><div><p class="dp-eyebrow">Benefits · Your Future</p><h2>Dream Pathway</h2><p>A shared plan for what matters to you.</p></div><div class="dp-actions"><button type="button" class="button" data-dp-refresh>Refresh</button>${can?`<button type="button" class="button dp-primary" data-dp-action="plan">${p?'Edit Pathway':'Set Up Pathway'}</button>`:''}</div></header>${!p?`<div class="dp-empty"><h3>Turn a Dream Into a Path</h3><p>${esc(d.dream||'Start with what the Talent would love to achieve.')}</p><p>Talent Management can agree the milestones, set a review date, and help with the next step.</p></div>`:`<div class="dp-plan"><p class="dp-eyebrow">${esc(p.status==='paused'?'Pathway Paused':'Our Shared Plan')}</p><h3>${esc(p.title)}</h3><p class="dp-description">${esc(p.description)}</p><div class="dp-facts"><span><small>Pathway Guide</small>${esc(p.ownerName||'Unassigned')}</span><span><small>Quarterly Check-In Due</small>${day(p.nextReviewOn)}</span><span><small>Progress</small>${m.filter(x=>x.status==='completed').length} of ${m.length} Milestones</span></div></div><div class="dp-section-heading"><h3>Milestones</h3>${can?'<button type="button" class="button" data-dp-action="milestone">+ Add Milestone</button>':''}</div><ol class="dp-milestones">${m.map((x,i)=>`<li class="dp-${esc(x.status)}"><span class="dp-step">${x.status==='completed'?'✓':i+1}</span><div><div class="dp-section-heading"><h4>${esc(x.title)}</h4><span class="dp-status">${esc(states[x.status])}</span></div><p class="dp-description">${esc(x.description)}</p><p class="dp-date">Target: ${day(x.targetDate)}</p>${x.progressNote?`<p class="dp-progress"><strong>Progress Update</strong>${esc(x.progressNote)}</p>`:''}${can?`<div class="dp-actions"><button type="button" class="button" data-dp-action="milestone" data-id="${x.id}">Edit Milestone</button><button type="button" class="button" data-dp-action="task" data-id="${x.id}">Add Follow-Up Task</button></div>`:''}</div></li>`).join('')||'<li class="dp-empty">No milestones yet. Add the first manageable step.</li>'}</ol>
  ${can?`<section class="dp-internal"><div class="dp-section-heading"><div><p class="dp-eyebrow">Staff Only</p><h3>Research & Follow-Ups</h3></div><button type="button" class="button" data-dp-action="task">+ Add Task</button></div><p>Assigned work appears in My Tasks. Internal task details are not shown to the Talent.</p>${(d.tasks||[]).map(t=>`<div class="dp-task"><div>${t.canOpen!==false?`<a href="#tasks/${t.id}">${esc(t.title)}</a>`:`<strong>${esc(t.title)}</strong>`}${t.milestoneTitle?`<small>${esc(t.milestoneTitle)}</small>`:''}</div><span>${esc(t.status)} · ${day(t.dueDate)}</span></div>`).join('')||'<p>No follow-up tasks have been created.</p>'}</section>`:''}
  <section class="dp-meetings"><div class="dp-section-heading"><h3>Check-Ins & Meetings</h3>${can?`<button type="button" class="button dp-primary" data-dp-action="meeting"${p.status==='paused'?' disabled title="Resume the pathway before scheduling"':''}>Schedule Meeting</button>`:''}</div><p>Quarterly reviews keep the plan moving. Add a separate follow-up whenever it is helpful.</p>${(d.meetings||[]).map(x=>`<article class="dp-meeting"><div class="dp-section-heading"><h4>${x.kind==='quarterly'?'Quarterly Dream Check-In':'Dream Follow-Up'}</h4><span class="dp-status">${esc(x.status)}</span></div><p>${when(x.startsAt)} · ${x.durationMinutes} minutes · ${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)} (Your Time)</p><p>${esc((x.attendeeNames||[]).join(', '))}</p><p class="dp-date">${x.status==='cancelled'?(x.calendarStatus==='synced'?'Calendar cancellation complete':'Calendar cancellation needs attention'):(x.calendarStatus==='synced'?'Calendar invitation sent':x.calendarStatus==='pending'?'Calendar update pending':x.calendarStatus==='sync_failed'?'Calendar update needs attention':'Calendar not connected')}</p>${x.joinUrl&&x.status==='scheduled'?`<a class="button" href="${esc(x.joinUrl)}" target="_blank" rel="noopener noreferrer">Join Teams Meeting</a>`:''}${x.summary?`<p class="dp-progress"><strong>Agreed Summary</strong>${esc(x.summary)}</p>`:''}${can&&x.status==='scheduled'?`<div class="dp-actions"><button type="button" class="button" data-dp-action="complete" data-id="${x.id}"${x.calendarStatus!=='synced'||Date.parse(x.startsAt)>Date.now()?' disabled title="Available after the synced meeting starts"':''}>Record Check-In</button><button type="button" class="button" data-dp-action="cancel" data-id="${x.id}">Cancel Meeting</button></div>`:''}${can&&x.status!=='completed'&&x.calendarStatus!=='synced'?`<button type="button" class="button" data-dp-retry="${x.id}">Retry Calendar Sync</button>`:''}</article>`).join('')||'<div class="dp-empty">No meetings scheduled yet.</div>'}</section>
  ${can&&(d.history||[]).length?`<details class="dp-history"><summary>Pathway History</summary>${d.history.map(x=>`<p><strong>${esc(x.summary)}</strong><br>${when(x.at)} · ${esc(x.actorName)}</p>`).join('')}</details>`:''}`}
  <p class="dp-privacy">Private to the Talent, Talent Management, and Administrators. Milestone progress is not a performance score or a funding balance.</p><p class="dp-feedback" role="status"></p></section>`;
 }
 const field=(label,name,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;
 const area=(label,name,value='',extra='')=>`<label>${label}<textarea name="${name}" ${extra}>${esc(value)}</textarea></label>`;
 function form(action,d,id){const p=d.plan||{},m=(d.milestones||[]).find(x=>x.id===id)||{},team=d.staff||[],options=team.filter(u=>['admin','talent_management'].includes(u.role)&&u.ready!==false).map(u=>`<option value="${u.id}" ${u.id===p.ownerId?'selected':''}>${esc(u.name)}</option>`).join('');
  if(action==='plan')return field('Dream Title','title',p.title||'','required maxlength="160"')+area('Our Agreed Path','description',p.description||d.dream,'required maxlength="4000"')+`<label>Pathway Guide<select name="ownerId" required>${options}</select></label>`+field('First Quarterly Review Due','anchorDate',p.anchorDate||'','type="date" required'+(p.id?' readonly':''))+`<label>Pathway Status<select name="status"><option value="active">Active</option><option value="paused" ${p.status==='paused'?'selected':''}>Paused</option></select></label><p>Reviews follow three-calendar-month periods from this date. The first date is retained so late meetings do not silently move later review periods.</p>`;
  if(action==='milestone')return field('Milestone Title','title',m.title,'required maxlength="160"')+area('What This Step Involves','description',m.description,'required maxlength="3000"')+`<div class="dp-form-grid">${field('Target Date (Optional)','targetDate',m.targetDate,'type="date"')}${field('Position on Path','position',m.position||(d.milestones.length+1),'type="number" min="1" max="100" step="1" required')}</div><label>Progress<select name="status">${Object.entries(states).map(([k,v])=>`<option value="${k}" ${k===m.status?'selected':''}>${v}</option>`).join('')}</select></label>`+area('Progress Update (Visible to Talent)','progressNote',m.progressNote,'maxlength="3000"');
  if(action==='task')return'<p class="dp-internal-note">Staff-only research or follow-up. Avoid medical, financial, or family details in task titles and notifications.</p>'+field('Task Title','title','','required maxlength="160"')+area('Instructions','details','','required maxlength="4000"')+field('Due Date','dueDate','','type="date" required')+`<label>Milestone (Optional)<select name="milestoneId"><option value="">Whole Pathway</option>${d.milestones.map(x=>`<option value="${x.id}" ${x.id===id?'selected':''}>${esc(x.title)}</option>`).join('')}</select></label><fieldset><legend>Assign to Staff</legend>${team.filter(u=>['admin','talent_management'].includes(u.role)&&u.ready!==false).map(u=>`<label class="dp-check"><input type="checkbox" name="assigneeIds" value="${u.id}" ${u.id===p.ownerId?'checked':''}>${esc(u.name)}</label>`).join('')}</fieldset>`;
  if(action==='meeting')return`<label>Meeting Type<select name="kind"><option value="quarterly">Quarterly Dream Check-In</option><option value="follow_up">General Follow-Up</option></select></label>${field('Date & Time','localStart','','type="datetime-local" required')}<p>Times are entered in ${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}. Invitations display in each attendee’s calendar time zone.</p><label>Duration<select name="durationMinutes"><option value="30">30 Minutes</option><option value="45">45 Minutes</option><option value="60">60 Minutes</option></select></label><fieldset><legend>Company Attendees</legend>${team.map(u=>`<label class="dp-check"><input type="checkbox" name="attendeeIds" value="${u.id}" ${u.id===p.ownerId?'checked':''}>${esc(u.name)}</label>`).join('')}</fieldset><p>The Talent is included automatically. Calendar titles and email text will not include private dream details.</p>`;
  if(action==='complete')return area('Agreed Summary (Visible to Talent)','summary','','required maxlength="4000"')+'<p>Completing a quarterly check-in advances the next due date by one three-month review period. General follow-ups do not change it.</p>';
  return '<p>Cancel this meeting and send a calendar cancellation to its attendees? The pathway and completed milestones will stay unchanged.</p>';
 }
 async function request(applicantId,body){const client=w.soroSupabase,scope=()=>JSON.stringify([w.soroCurrentAccess?.user_id,w.soroCurrentAccess?.organization_id,w.soroCurrentAccess?.role]),captured=scope(),uid=w.soroCurrentAccess?.user_id;const check=()=>{if(client!==w.soroSupabase||captured!==scope())throw new Error('Your workspace changed. Reopen this pathway.');};const {data}=await client.auth.getSession();check();if(!data?.session?.access_token||data.session.user?.id!==uid)throw new Error('Sign in again to open the pathway.');const r=await fetch(endpoint+(body?'':'?applicantId='+encodeURIComponent(applicantId)),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+data.session.access_token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});const v=await r.json();check();if(!r.ok)throw new Error(v.message||'The pathway could not be loaded.');return v;}
 function mount(target,{applicantId,adapter,isCurrent=()=>true,summaryTarget}={}){let data=null,busy=false,seq=0;const current=()=>target.isConnected&&isCurrent();
  const send=b=>adapter?adapter(b):request(applicantId,b);
  function draw(){if(!current())return;target.innerHTML=markup(data);if(summaryTarget?.isConnected)summaryTarget.innerHTML=summary(data);target.querySelector('[data-dp-refresh]').onclick=load;target.querySelectorAll('[data-dp-action]').forEach(b=>b.onclick=()=>edit(b.dataset.dpAction,b.dataset.id));target.querySelectorAll('[data-dp-retry]').forEach(b=>b.onclick=()=>saveDirect('retry_meeting',b.dataset.dpRetry));}
  async function load(){const n=++seq;try{const v=await send();if(n!==seq||!current())return;data=v;draw();}catch(e){if(n===seq&&current()){if(summaryTarget?.isConnected)summaryTarget.innerHTML='<p>Dream Pathway could not be loaded. Open Benefits to retry.</p>';target.innerHTML=`<div class="dp-empty"><p>${esc(e.message)}</p><button class="button" type="button" data-retry>Try Again</button></div>`;target.querySelector('[data-retry]').onclick=load;}}}
  async function saveDirect(action,id){if(busy)return;busy=true;try{data=await send({action,applicantId,requestId:w.crypto.randomUUID(),version:data.plan.version,meetingId:id});draw();}catch(e){target.querySelector('.dp-feedback').textContent=e.message;}finally{busy=false;}}
  function edit(action,id){if(!data.canManage||busy)return;const dialog=document.createElement('dialog');dialog.className='dp-dialog';const titles={plan:data.plan?'Edit Dream Pathway':'Set Up Dream Pathway',milestone:id?'Edit Milestone':'Add Milestone',task:'Create Follow-Up Task',meeting:'Schedule Dream Meeting',complete:'Record Dream Check-In',cancel:'Cancel Meeting'};dialog.innerHTML=`<form><header><div><p class="dp-eyebrow">Dream Pathway</p><h2>${titles[action]}</h2></div><button type="button" data-close aria-label="Close">×</button></header><div class="dp-form">${form(action,data,id)}<p role="alert" data-error></p></div><footer><button class="button" type="button" data-close>Cancel</button><button class="button dp-primary" type="submit">${action==='meeting'?'Schedule & Send Invite':action==='cancel'?'Cancel Meeting':'Save'}</button></footer></form>`;document.body.append(dialog);dialog.showModal();let key=w.crypto.randomUUID();dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>dialog.close());dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!current()){dialog.close();return;}if(busy)return;const fd=new FormData(e.target),b={action,applicantId,requestId:key,version:data.plan?.version||0};for(const [k,v]of fd)b[k]=v;
   if(action==='milestone'){b.milestoneId=id||null;b.position=Number(b.position);b.targetDate=b.targetDate||null;}
   if(action==='task'){b.assigneeIds=fd.getAll('assigneeIds');b.milestoneId=b.milestoneId||null;if(!b.assigneeIds.length||b.assigneeIds.length>30){dialog.querySelector('[data-error]').textContent='Choose between 1 and 30 staff members.';return;}}
   if(action==='meeting'){b.attendeeIds=fd.getAll('attendeeIds');if(!b.attendeeIds.length){dialog.querySelector('[data-error]').textContent='Choose at least one company attendee.';return;}b.startsAt=new Date(b.localStart).toISOString();delete b.localStart;b.timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;b.durationMinutes=Number(b.durationMinutes);}
   if(['cancel','complete'].includes(action))b.meetingId=id;
   busy=true;const submit=dialog.querySelector('[type="submit"]');submit.disabled=true;submit.textContent=action==='meeting'?'Scheduling…':'Saving…';try{const v=await send(b);if(!current()){dialog.close();return;}data=v;dialog.close();draw();w.soroTaskCenter?.refresh?.({silent:true});}catch(error){dialog.querySelector('[data-error]').textContent=error.message;submit.disabled=false;submit.textContent='Try Again';}finally{busy=false;}
  };}
  load();return{refresh:load};
 }
 return{summary,markup,mount,states};
});
