/* Staff-only placement closing. The original placement and its evidence remain intact. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SoroPlacementEnding=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
 'use strict';
 const ENDPOINT='/.netlify/functions/placement-ending',ROLES=new Set(['admin','talent_management']);
 const CHECKS=Object.freeze({handover:'Work handover completed',access:'Client-system access removal confirmed',time:'Final work sessions reviewed'});
 const REASONS=Object.freeze({assignment_complete:'Assignment completed',client_request:'Client requested a change',talent_request:'Talent requested a change',role_change:'Role or business needs changed',other:'Other'});
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
 const day=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
 let host,options={},data,controller,generation=0,dialog,busy=false,activeRequest=null,filter='current',search='';
 const actual=()=>root.soroCurrentAccess||{};
 const scope=()=>[actual().user_id,actual().organization_id,actual().role,actual().active,actual().must_change_password,root.adminPreviewingNonAdminWorkspace?.(),options.role].join('|');
 function validate(v){
  if(!v||!ROLES.has(v.viewerRole)||!Array.isArray(v.placements)||v.placements.length>200||!Number.isSafeInteger(v.total)||v.total<0)throw new Error('The placement list could not be verified. Refresh and try again.');
  for(const p of v.placements){if(!uuid(p.id)||!uuid(p.applicantId)||typeof p.talentName!=='string'||typeof p.clientName!=='string'||!day(p.today)||typeof p.canPlan!=='boolean'||!Number.isSafeInteger(p.openSessions))throw new Error('The placement details could not be verified.');
   if(p.ending&&(!['planned','completed','cancelled'].includes(p.ending.status)||!Number.isSafeInteger(p.ending.version)||!day(p.ending.lastDate)||!REASONS[p.ending.reason]||!['review','bench'].includes(p.ending.talentNextStep)||Object.values(p.ending.checklist||{}).some(x=>typeof x!=='boolean')))throw new Error('The closing details could not be verified.');
  }return v;
 }
 const date=v=>day(v)?new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(v+'T00:00:00Z')):'Not set';
 function blockers(p){const e=p.ending,r=[];if(!e||e.status!=='planned')return ['Save an end plan first.'];if(e.lastDate>p.today)r.push('The final working date has not arrived.');if(Object.keys(CHECKS).some(k=>e.checklist[k]!==true))r.push('Complete the three closing checks.');if(!p.healthcareReady)r.push('Resolve the healthcare cancellation or continuation review.');if(p.openSessions>0)r.push('Close or correct every open work session first.');return r;}
 function markup(v){
  const rows=v.placements.filter(p=>(filter==='all'||filter==='ending'&&p.ending?.status==='planned'||filter==='ended'&&p.status==='ended'||filter==='current'&&p.status!=='ended')&&`${p.talentName} ${p.clientName}`.toLowerCase().includes(search.toLowerCase()));
  return `<main class="page pe-page"><header class="pe-heading"><div><p class="eyebrow">${v.viewerRole==='admin'?'Admin Panel':'Talent Management Panel'}</p><h1>Placements</h1><p>Current assignments, last working dates, and offboarding.</p></div><button class="pe-button" data-pe="refresh">Refresh</button></header>
   <div class="pe-metrics"><div><span>Current assignments · loaded</span><strong>${v.placements.filter(p=>p.status!=='ended').length}</strong></div><div><span>Offboarding in progress · loaded</span><strong>${v.placements.filter(p=>p.ending?.status==='planned').length}</strong></div><div><span>Completed · loaded</span><strong>${v.placements.filter(p=>p.ending?.status==='completed').length}</strong></div></div>
   <section class="pe-panel"><div class="pe-toolbar"><label>Find a placement<input type="search" data-pe-search value="${esc(search)}" placeholder="Talent or client name"></label><label>Show<select data-pe-filter>${[['current','Current placements'],['ending','Offboarding in progress'],['ended','Ended placements'],['all','All placements']].map(([k,n])=>`<option value="${k}"${filter===k?' selected':''}>${n}</option>`).join('')}</select></label></div><div class="pe-list">${rows.map(p=>`<article class="pe-card"><div class="pe-card-heading"><div><h2>${esc(p.talentName)}</h2><p>${esc(p.clientName)}</p></div><span class="pe-status${p.ending?.status==='planned'?' is-ending':''}">${p.ending?.status==='planned'?'Offboarding in progress':esc(p.status.replace(/_/g,' '))}</span></div><dl><div><dt>Started</dt><dd>${date(p.startDate)}</dd></div><div><dt>${p.ending?.status==='planned'?'Planned last day':'Last working day'}</dt><dd>${date(p.ending?.status==='cancelled'?p.endDate:p.ending?.lastDate||p.endDate)}</dd></div><div><dt>Schedule</dt><dd>${esc(p.schedule||'Not recorded')}</dd></div></dl><footer>${p.hiringRequestId?`<button class="pe-link" data-pe="setup" data-id="${p.id}">Placement details</button>`:''}<button class="pe-link" data-pe="work" data-id="${p.id}">Work Log</button>${p.ending?.status==='completed'?`<button class="pe-button" data-pe="open" data-id="${p.id}">View closing record</button>`:p.canPlan?`<button class="pe-button${p.ending?.status==='planned'?' is-primary':''}" data-pe="open" data-id="${p.id}">${p.ending?.status==='planned'?'Continue offboarding':'End placement'}</button>`:''}</footer></article>`).join('')||'<div class="pe-empty"><h2>No placements in this view</h2><p>Confirmed assignments will appear here. No sample records are added to your account.</p></div>'}</div><p class="pe-note">${v.placements.length} of ${v.total} placements loaded${v.total>v.placements.length?' · Open a specific placement from its client workspace to view an older record.':''}. Ending an assignment retains its work history and documents.</p></section></main>`;
 }
 async function request(method,body,query={}){
  const ctx={host,generation,scope:scope(),client:root.soroSupabase,controller};const check=()=>{if(ctx.host!==host||!host?.isConnected||ctx.generation!==generation||ctx.scope!==scope()||ctx.client!==root.soroSupabase||ctx.controller!==controller)throw Object.assign(new Error('The workspace changed. Reopen the placement.'),{name:'AbortError'});};
  if(options.adapter){const v=await options.adapter(method,body,query);check();return v;}
  if(options.preview||root.adminPreviewingNonAdminWorkspace?.())throw new Error('Live placement records are not loaded while previewing another role.');
  const {data:{session}={},error}=await ctx.client?.auth?.getSession?.()||{};check();if(error||!session?.access_token||session.user?.id!==actual().user_id||!ROLES.has(actual().role)||actual().active===false||actual().must_change_password===true)throw new Error('Sign in with Admin or Talent Management access.');
  const r=await root.fetch(ENDPOINT+(Object.keys(query).length?'?'+new URLSearchParams(query):''),{method,headers:{Authorization:'Bearer '+session.access_token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal});const v=await r.json();check();if(!r.ok)throw new Error(v.message||'The placement could not be updated.');return v;
 }
 function close(){if(busy)return;if(dialog){dialog.close();dialog.remove();dialog=null;}activeRequest=null;}
 function unmount(){generation++;controller?.abort();busy=false;close();host=null;data=null;}
 function render(){if(!host||!data)return;host.innerHTML=markup(data);host.querySelector('[data-pe-filter]').onchange=e=>{filter=e.target.value;render();};host.querySelector('[data-pe-search]').oninput=e=>{search=e.target.value;const start=e.target.selectionStart;render();const input=host.querySelector('[data-pe-search]');input.focus();try{input.setSelectionRange(start,start);}catch{}};host.onclick=e=>{const b=e.target.closest('[data-pe]');if(!b)return;const p=data.placements.find(x=>x.id===b.dataset.id);if(b.dataset.pe==='refresh')load();if(b.dataset.pe==='open'&&p)open(p);if(b.dataset.pe==='setup'&&p)root.dispatchEvent(new CustomEvent('soro:client-placement-open',{detail:{requestId:p.hiringRequestId}}));if(b.dataset.pe==='work'&&p)root.dispatchEvent(new CustomEvent('soro:placement-work-log-open',{detail:{placementId:p.id}}));};}
 async function load(openId){const g=generation;try{data=validate(await request('GET',null,openId?{placementId:openId}:{}));if(g!==generation)return;render();if(openId){const p=data.placements.find(p=>p.id===openId);if(p)open(p);}}catch(e){if(e.name!=='AbortError'&&g===generation&&host)host.innerHTML=`<main class="page pe-page"><section class="pe-panel" role="alert"><h1>Placements unavailable</h1><p>${esc(e.message)}</p><button class="pe-button" data-pe-retry>Try again</button></section></main>`;host?.querySelector('[data-pe-retry]')?.addEventListener('click',()=>load(openId));}}
 async function mutate(body){
  if(busy)return;busy=true;const d=dialog,g=generation;d.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=true);
  const fingerprint=JSON.stringify(body);if(activeRequest?.fingerprint!==fingerprint)activeRequest={fingerprint,requestId:root.crypto.randomUUID()};
  try{const v=validate(await request('POST',{...body,requestId:activeRequest.requestId}));if(dialog!==d||generation!==g)return;
   const incoming=new Map(v.placements.map(p=>[p.id,p]));data={...data,placements:data.placements.map(p=>incoming.get(p.id)||p)};
   busy=false;close();render();const p=data.placements.find(p=>p.id===body.placementId);if(p)open(p);root.dispatchEvent(new CustomEvent('soro:client-placement-updated'));
  }catch(e){if(dialog!==d||generation!==g)return;busy=false;if(e.name!=='AbortError'){d.querySelector('[data-pe-error]').textContent=e.message;d.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=false);}}
 }
 function open(p){
  close();const e=p.ending,planned=e?.status==='planned',completed=e?.status==='completed',version=e?.version||0;const problems=blockers(p);
  dialog=root.document.createElement('dialog');dialog.className='pe-dialog';dialog.innerHTML=`<header><div><p class="eyebrow">${esc(p.clientName)}</p><h2>${completed?'Placement ended':planned?'Complete offboarding':'Plan the last working day'}</h2><p>${esc(p.talentName)}</p></div><button class="pe-button pe-close" data-pe-close aria-label="Close offboarding">×</button></header><div class="pe-dialog-body">
   ${completed?`<div class="pe-complete"><strong>Closed ${date(e.lastDate)}</strong><p>${e.talentNextStep==='bench'?'Talent returned to Available Talent.':'Talent moved to review and remains off the available bench.'}</p>${e.replacementRequestId?'<p>A separate replacement hiring request was created for Sales.</p>':''}<p>Work sessions, shared screenshots, documents, and the original placement are retained.</p></div>`:''}
   <div class="pe-columns"><section><h3>End plan</h3><form data-pe-plan><label>Last working date<input type="date" name="lastDate" min="${esc(p.startDate)}" value="${esc(e?.status!=='cancelled'&&e?.lastDate||p.today)}" required${completed?' disabled':''}></label><p class="pe-note">${esc(p.timezone)}. ${completed?'Recorded last working date for this closed placement.':'The placement remains active until you complete offboarding; it does not end automatically.'}</p><label>Reason · internal only<select name="reason"${completed?' disabled':''}>${Object.entries(REASONS).map(([k,n])=>`<option value="${k}"${e?.reason===k?' selected':''}>${n}</option>`).join('')}</select></label><label>Internal note (optional)<textarea name="note" maxlength="2000" rows="3"${completed?' disabled':''}>${esc(e?.note||'')}</textarea></label><label>Talent’s next step<select name="talentNextStep"${completed?' disabled':''}><option value="review"${e?.talentNextStep!=='bench'?' selected':''}>Keep off bench · Talent Management review</option><option value="bench"${e?.talentNextStep==='bench'?' selected':''}>Return to Available Talent · eligibility confirmed</option></select></label><p class="pe-note">Return to bench only after confirming the Talent is available and still meets your requirements.</p><label class="pe-check"><input type="checkbox" name="replacement"${e?.replacement?' checked':''}${completed?' disabled':''}><span>Client needs a replacement<p>${completed?'The replacement request is retained in the client’s hiring pipeline.':'A new one-seat request will be created in the client’s hiring pipeline when offboarding is completed.'} No replacement is selected automatically.</p></span></label>${!completed?'<button class="pe-button" type="submit">Save end plan</button>':''}</form></section>
   <section><h3>Closing checklist</h3>${planned||completed?`<form data-pe-checks>${Object.entries(CHECKS).map(([k,n])=>`<label class="pe-check"><input type="checkbox" name="${k}"${e.checklist[k]?' checked':''}${completed?' disabled':''}><span>${n}</span></label>`).join('')}${!completed?'<button class="pe-button" type="submit">Save checklist</button>':''}</form>`:'<p class="pe-note">Save the end plan to begin the closing checks.</p>'}<p class="pe-note">These checks record work completed by your team. Soro does not remove access from external client systems.</p><div class="pe-health"><h4>Healthcare review</h4><p>${p.healthcareReady?'Cancellation or continuation review recorded.':'Confirm cancellation, continued coverage, or that there is no coverage to change.'}</p>${!completed&&planned?'<div data-pe-healthcare></div>':''}</div><div class="pe-health"><h4>Final time review</h4><p>${p.openSessions?`${p.openSessions} work ${p.openSessions===1?'session is':'sessions are'} still open.`:'No open work sessions.'} Attendance remains historical and is not a final-pay calculation.</p></div></section></div>
   <p data-pe-error role="alert"></p>${planned?`<div class="pe-final"><h3>Ready to close?</h3>${problems.length?`<ul>${problems.map(m=>`<li>${esc(m)}</li>`).join('')}</ul>`:'<p>All recorded checks are complete. Confirm that no further work will be logged against this assignment.</p>'}<label class="pe-check"><input type="checkbox" data-pe-confirm><span>I confirm the last work has finished and this placement should end.</span></label><button class="pe-button is-primary" data-pe-finish${problems.length?' disabled':''}>Complete offboarding</button><button class="pe-link" data-pe-reload>Refresh checks</button></div>`:''}
   ${planned?'<details class="pe-cancel"><summary>Cancel this end plan</summary><p>The placement will stay active. This is only available while the healthcare review is still pending; it does not restore coverage that was already cancelled.</p><button class="pe-button" data-pe-cancel>Cancel end plan</button></details>':''}</div>`;
  root.document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-pe-close]').onclick=close;dialog.addEventListener('cancel',ev=>{ev.preventDefault();close();});
  dialog.querySelector('[data-pe-plan]').onsubmit=ev=>{ev.preventDefault();if(completed)return;const f=new root.FormData(ev.target);mutate({action:'plan',placementId:p.id,version,lastDate:f.get('lastDate'),reason:f.get('reason'),note:f.get('note'),talentNextStep:f.get('talentNextStep'),replacement:f.get('replacement')==='on'});};
  const checks=dialog.querySelector('[data-pe-checks]');if(checks)checks.onsubmit=ev=>{ev.preventDefault();if(completed)return;const f=new root.FormData(ev.target);mutate({action:'checklist',placementId:p.id,version,checklist:Object.fromEntries(Object.keys(CHECKS).map(k=>[k,f.get(k)==='on']))});};
  const finish=dialog.querySelector('[data-pe-finish]');if(finish)finish.onclick=()=>{if(problems.length||!dialog.querySelector('[data-pe-confirm]').checked){dialog.querySelector('[data-pe-error]').textContent='Confirm the final work is finished before completing offboarding.';return;}mutate({action:'complete',placementId:p.id,version,confirm:true});};
  dialog.querySelector('[data-pe-reload]')?.addEventListener('click',()=>{close();load(p.id);});
  dialog.querySelector('[data-pe-cancel]')?.addEventListener('click',()=>mutate({action:'cancel',placementId:p.id,version}));
  const health=dialog.querySelector('[data-pe-healthcare]');if(health){
   const refreshHint=root.document.createElement('p');refreshHint.className='pe-note';refreshHint.textContent='After saving a healthcare result, choose Refresh checks below to update closing readiness.';health.parentElement.append(refreshHint);
   if(options.adapter&&options.healthcareAdapter&&root.SoroTalentHealthcare?.mount)root.SoroTalentHealthcare.mount(health,{applicantId:p.applicantId,placementId:p.id,compact:true,preview:true,adapter:options.healthcareAdapter,onOpenBenefits:()=>{dialog.querySelector('[data-pe-error]').textContent='This sample has no enrolled coverage. In the live portal, this opens the Talent’s Benefits tab.';}});
   else if(options.adapter)health.innerHTML='<p class="pe-note">Healthcare review is not connected in this sample.</p>';
   else if(root.SoroTalentHealthcare?.mount)root.SoroTalentHealthcare.mount(health,{applicantId:p.applicantId,placementId:p.id,compact:true,onOpenBenefits:()=>{close();root.SoroTalentHealthcare.requestOpen(p.applicantId);options.onOpenTalent?.(p.applicantId);}});
   else health.innerHTML='<p>Open the Talent profile → Benefits to complete the healthcare review, then refresh these checks.</p>';
   if(p.healthcareReady){const recover=root.document.createElement('details');recover.innerHTML='<summary>Need to change this end plan?</summary><p class="pe-note">Reopen a no-coverage or continuation review before changing dates or cancelling. The earlier result is retained; coverage itself is not changed. Carrier-confirmed cancellations require a separate coverage review.</p><button class="pe-button">Reopen healthcare review</button>';health.parentElement.append(recover);recover.querySelector('button').onclick=()=>mutate({action:'reopen_healthcare',placementId:p.id,version});}
  }
 }
 function mount(target,opts={}){unmount();host=target;options=opts;controller=new root.AbortController();filter='current';search='';if(!ROLES.has(opts.role||actual().role)){host.innerHTML='<main class="page pe-page"><p>Admin or Talent Management access is required.</p></main>';return;}host.innerHTML='<main class="page pe-page"><p role="status">Loading placements…</p></main>';return load(opts.placementId);}
 return Object.freeze({mount,unmount,markup,validate,blockers,canManage:role=>ROLES.has(role),CHECKS,REASONS});
});
