/* Authorized task details, per-person view receipts, and sign-in-safe task links. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.soroTaskDetail=api;}(typeof globalThis!=='undefined'?globalThis:this,function(root){
  'use strict';
  const ENDPOINT='/.netlify/functions/task-detail';
  const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  const progressLabels={not_started:'Not Started',in_progress:'In Progress',blocked:'Blocked',completed:'Completed',submitted:'Response Submitted',closed:'Closed'};
  let pendingId=parseHash(root.location?.hash),dialog=null,loadedId='',generation=0,activeScope='',markViewed=null;
  function parseHash(hash){const id=String(hash||'').match(/^#tasks\/([^/?#]+)$/)?.[1];return UUID.test(id||'')?id.toLowerCase():null;}
  function escape(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function scope(){const a=root.soroCurrentAccess;return JSON.stringify([a?.user_id,a?.organization_id,a?.role,root.currentAuthenticatedRole?.()]);}
  function remember(){const id=parseHash(root.location?.hash);if(id)pendingId=id;return pendingId;}
  function restore(){if(!pendingId)return false;const a=root.soroCurrentAccess;if(!a?.user_id||a.must_change_password||a.active===false)return false;if(!root.viewAllowedForAuthenticatedRole?.('tasks')){pendingId=null;return false;}const id=pendingId;pendingId=null;root.history.replaceState({},'',`#tasks/${id}`);root.dispatchEvent(new root.CustomEvent('soro:task-route',{detail:{taskId:id}}));return true;}
  function close(){generation++;loadedId='';markViewed=null;if(dialog){dialog.close();dialog.remove();dialog=null;}}
  function navigate(id){if(!UUID.test(id||''))return;pendingId=id;root.history.pushState({},'',`#tasks/${id}`);root.dispatchEvent(new root.CustomEvent('soro:task-route',{detail:{taskId:id}}));sync();}
  async function request(body,guard=()=>{}){
    const client=root.soroSupabase,captured=scope(),user=root.soroCurrentAccess?.user_id;
    const check=()=>{guard();if(client!==root.soroSupabase||scope()!==captured)throw new Error('Your workspace changed. Reopen the task.');};
    check();const result=await client?.auth?.getSession();check();
    if(!result?.data?.session?.access_token||result.data.session.user?.id!==user)throw new Error('Sign in again to open this task.');
    const response=await root.fetch(ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${result.data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});
    const value=await response.json();check();if(!response.ok)throw new Error(value.message||'The task could not be loaded.');return value;
  }
  function personOptions(people,selected){return people.map(p=>`<label class="task-person"><input type="checkbox" name="assigneeIds" value="${escape(p.userId)}"${selected.includes(p.userId)?' checked':''}><span>${escape(p.name)}</span></label>`).join('');}
  function historyMarkup(history){return `<section class="task-history"><h3>Task History</h3>${history.length?`<ol>${history.map(h=>`<li><div><strong>${escape(h.actor)}</strong><time>${escape(new Date(h.at).toLocaleString())}</time></div><p>${escape(h.summary)}</p>${h.note?`<p class="task-preserve">${escape(h.note)}</p>`:''}</li>`).join('')}</ol>`:'<p>No changes recorded yet.</p>'}</section>`;}
  function markup(data){const t=data.task,applicant=t.kind==='applicant_request',editable=t.canEditDetails,progress=t.progress||'not_started',managed=t.source?.kind==='interview_result'; data={...data,assignees:[...new Map([...(data.assignees||[]),...(t.assignees||[])].map(p=>[p.userId,p])).values()]};
    return `<form class="task-detail-form"><header><div><p class="eyebrow">${applicant?'Application Follow-Up':'Shared Task'}</p><h2>${escape(t.title)}</h2><p>${applicant?'Your response goes to the Talent Management team.':'One task, one shared progress status.'}</p></div><button type="button" class="button" data-task-close aria-label="Close task">×</button></header><div class="task-detail-body"><div class="task-detail-grid"><section><h3>Task Details</h3>${editable?`<label>Task Name<input name="title" required maxlength="160" value="${escape(t.title)}"></label><label>Instructions<textarea name="details" maxlength="4000" rows="5">${escape(t.details)}</textarea></label><label>Related To<input name="relatedLabel" maxlength="200" value="${escape(t.relatedLabel)}"></label>`:`<p class="task-preserve">${escape(t.details||'No additional instructions.')}</p>`}${applicant?`<p><a href="#talent-my-profile">My Profile</a> · <a href="#documents">Document Center</a></p><label>Your Response<textarea name="response" maxlength="4000" rows="5"${t.canUpdateProgress?'':' disabled'}>${escape(t.response)}</textarea></label>`:''}${managed?'<p class="task-detail-callout">Progress is updated when the interview result is recorded in the Talent Review Queue.</p>':''}</section><section><h3>Progress & Assignment</h3><label>Status<select name="progress"${t.canUpdateProgress&&!applicant?'':' disabled'}>${Object.entries(progressLabels).filter(([k])=>applicant?['not_started','submitted','closed'].includes(k):!['submitted','closed'].includes(k)).map(([k,v])=>`<option value="${k}"${k===progress?' selected':''}>${v}</option>`).join('')}</select></label><div class="task-detail-pair"><label>Due Date<input type="date" name="dueDate" value="${escape(t.dueDate||'')}"${editable?'':' disabled'}></label><label>Priority<select name="priority"${editable?'':' disabled'}>${['low','normal','high','urgent'].map(p=>`<option value="${p}"${p===t.priority?' selected':''}>${p[0].toUpperCase()+p.slice(1)}</option>`).join('')}</select></label></div>${!applicant?`<fieldset class="task-people"${editable?'':' disabled'}><legend>Assigned To</legend>${personOptions(editable?data.assignees:(t.assignees||[]),(t.assignees||[]).map(p=>p.userId))}</fieldset><p class="task-detail-help">Created by ${escape(t.createdBy?.name||'The Soro Group')}</p>`:''}${t.canUpdateProgress&&!applicant?'<label>Update Note <span>(Optional)</span><textarea name="note" maxlength="2000" rows="3" placeholder="Share an update with everyone assigned"></textarea></label>':''}</section></div>${historyMarkup(data.history||[])}</div><footer><p data-task-message role="status"></p><button type="button" class="button" data-task-close>Close</button>${t.canUpdateProgress||editable?`<button type="submit" class="button primary">${applicant?'Submit Response':'Save Changes'}</button>`:''}</footer></form>`;
  }
  async function open(id){if(loadedId===id&&dialog?.open){markViewed?.();return;}close();const n=generation,captured=scope();activeScope=captured;loadedId=id;const d=root.document.createElement('dialog');dialog=d;d.className='task-detail-dialog';d.innerHTML='<p class="task-detail-loading" role="status">Opening task…</p>';root.document.body.append(d);d.showModal();
    const guard=()=>{if(n!==generation||!d.open||scope()!==captured||parseHash(root.location.hash)!==id)throw new Error('Task view changed.');};
    const leave=()=>{close();pendingId=null;if(parseHash(root.location.hash)){root.history.replaceState({},'','#tasks');}};
    d.addEventListener('cancel',e=>{e.preventDefault();leave();});
    try{const data=await request({action:'get',taskId:id},guard);guard();pendingId=null;d.innerHTML=markup(data); if(!data.task.canAssign)d.querySelector('.task-people')?.setAttribute('disabled',''); if(data.task.canCloseRequest){const response=d.querySelector('[name="response"]');if(response){response.disabled=true;response.closest('label').firstChild.textContent='Applicant Response';}d.querySelector('[type="submit"]').textContent='Close Request';d.querySelector('a[href="#talent-my-profile"]')?.parentElement.remove();} d.querySelectorAll('[data-task-close]').forEach(b=>b.addEventListener('click',leave));
      const form=d.querySelector('form');let key=null,saving=false;
      form.addEventListener('input',()=>{if(!saving)key=null;});
      form.addEventListener('submit',async e=>{e.preventDefault();if(saving)return;saving=true;key=key||root.crypto.randomUUID();const values=new root.FormData(form),t=data.task;
        const patch=t.kind==='applicant_request'?(t.canCloseRequest?{closeRequest:true}:{response:String(values.get('response')||'')}):{progress:String(values.get('progress')||t.progress),note:String(values.get('note')||''),...(t.canEditDetails?{title:String(values.get('title')||''),details:String(values.get('details')||''),relatedLabel:String(values.get('relatedLabel')||''),dueDate:values.get('dueDate')||null,priority:values.get('priority'),...(t.canAssign?{assigneeIds:values.getAll('assigneeIds')}: {})}: {})};
        const controls=[...form.querySelectorAll('input,textarea,select,button[type="submit"]')],disabled=controls.map(c=>c.disabled);controls.forEach(c=>c.disabled=true);const message=form.querySelector('[data-task-message]');message.textContent='Saving…';
        try{await request({action:'save',taskId:id,expectedVersion:t.version,requestId:key,patch},guard);guard();loadedId='';await open(id);root.soroTaskCenter?.refresh?.({silent:true});}
        catch(error){if(n===generation){message.textContent=error.message;controls.forEach((c,i)=>c.disabled=disabled[i]);saving=false;}}
      });
      // A separate receipt: neither list loading nor notification clearing counts as viewing.
      await new Promise(resolve=>root.requestAnimationFrame(()=>root.requestAnimationFrame(resolve)));guard();
      let receiptDone=false,receiptPending=false;
      markViewed=async()=>{if(receiptDone||receiptPending||n!==generation||root.document.visibilityState!=='visible'||!d.getClientRects().length)return;receiptPending=true;
        try{await request({action:'view',taskId:id},guard);guard();receiptDone=true;root.soroTaskCenter?.refresh?.({silent:true});}
        catch{if(n===generation&&!saving)d.querySelector('[data-task-message]').textContent='Opened. Reconnect or reopen the task to clear the New marker.';}
        finally{receiptPending=false;}
      };
      await markViewed();
    }catch(error){if(n!==generation)return;d.innerHTML=`<div class="task-detail-loading"><h2>Task Unavailable</h2><p>${escape(error.message)}</p><button class="button" data-task-close>Close</button></div>`;d.querySelector('button').addEventListener('click',leave);}
  }
  function sync(){const a=root.soroCurrentAccess,id=parseHash(root.location?.hash);if(!id||!a?.user_id||a.must_change_password||a.active===false||root.adminPreviewingNonAdminWorkspace?.()){if(dialog)close();return;}if(activeScope&&activeScope!==scope())close();const app=root.document?.getElementById('app');if(app?.hidden||root.document?.visibilityState==='hidden')return;open(id);}
  root.addEventListener?.('soro-auth-changed',()=>{if(dialog&&activeScope!==scope())close();sync();});root.addEventListener?.('online',sync);root.addEventListener?.('hashchange',sync);root.addEventListener?.('popstate',sync);root.document?.addEventListener('visibilitychange',sync);
  return Object.freeze({parseHash,remember,restore,navigate,sync,close,request,markup,progressLabels});
}));
