/* Placement-scoped work sessions and intentionally shared work images. */
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.SoroWorkLog=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){
 'use strict';
 const ENDPOINT='/.netlify/functions/work-log',ROLES=new Set(['admin','talent_management','client_admin','client_reviewer','virtual_assistant']);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);
 const day=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v;
 const stamp=v=>typeof v==='string'&&Number.isFinite(Date.parse(v));
 let host=null,options={},workspace=null,generation=0,controller=null,busy=false,dialog=null,objectURL=null,activeMutation=null;
 const actual=()=>root.soroCurrentAccess||{};
 const scope=()=>[actual().user_id,actual().organization_id,actual().role,actual().active,actual().must_change_password,root.adminPreviewingNonAdminWorkspace?.(),options.role].join('|');
 function validate(v){
  const bad=()=>{throw new Error('The work log could not be verified. Please refresh.');};
  if(!v||!ROLES.has(v.viewerRole)||!stamp(v.generatedAt)||!Array.isArray(v.placements)||!Array.isArray(v.sessions)||!Array.isArray(v.requests)||!Array.isArray(v.images)||v.sessions.length>31||v.requests.length>100||v.images.length>200)bad();
  if(!Number.isSafeInteger(v.total)||v.total<0||!Number.isSafeInteger(v.offset)||v.offset<0)bad();
  for(const p of v.placements)if(!uuid(p.id)||typeof p.talentName!=='string'||typeof p.clientName!=='string'||typeof p.canShare!=='boolean'||typeof p.canRequest!=='boolean')bad();
  const ids=new Set(v.placements.map(p=>p.id));
  for(const s of v.sessions)if(!uuid(s.id)||!ids.has(s.placementId)||!day(s.workDate)||!stamp(s.startedAt)||(s.checkedOutAt!==null&&!stamp(s.checkedOutAt))||typeof s.timezone!=='string')bad();
  for(const r of v.requests)if(!uuid(r.id)||!ids.has(r.placementId)||!day(r.workDate)||!['requested','shared','cancelled'].includes(r.status)||typeof r.note!=='string')bad();
  for(const i of v.images)if(!uuid(i.id)||!ids.has(i.placementId)||!uuid(i.sessionId)||!stamp(i.sharedAt)||typeof i.note!=='string')bad();
  return v;
 }
 function time(value,zone){if(!value)return 'Not checked out';try{return new Intl.DateTimeFormat(undefined,{timeZone:zone,hour:'numeric',minute:'2-digit',month:'short',day:'numeric',timeZoneName:'short'}).format(new Date(value));}catch{return new Date(value).toISOString();}}
 function duration(s,now){const end=s.checkedOutAt||now,minutes=Math.max(0,Math.floor((Date.parse(end)-Date.parse(s.startedAt))/60000));return `${Math.floor(minutes/60)}h ${minutes%60}m`;}
 function stale(s,now){return !s.checkedOutAt&&Date.parse(now)-Date.parse(s.startedAt)>18*3600000;}
 function markup(v,filters={}){
  const talent=v.viewerRole==='virtual_assistant',client=['client_admin','client_reviewer'].includes(v.viewerRole),pending=v.requests.filter(r=>r.status==='requested');
  const getp=id=>v.placements.find(p=>p.id===id),minutes=v.sessions.reduce((n,s)=>n+(s.checkedOutAt?Math.max(0,(Date.parse(s.checkedOutAt)-Date.parse(s.startedAt))/60000):0),0);
  return `<main class="page work-log"><header class="wl-heading"><div><p class="eyebrow">${talent?'Talent Portal':client?'Client Portal':'Soro Operations'}</p><h1>Work Log</h1><p>Recorded work sessions and screenshots shared with the matched client.</p></div><button class="wl-button" data-wl="refresh">Refresh</button></header>
   <div class="wl-summary"><div><span>Completed time · this page</span><strong>${Math.floor(minutes/60)}h ${Math.floor(minutes%60)}m</strong></div><div><span>Open sessions · this page</span><strong>${v.sessions.filter(s=>!s.checkedOutAt).length}</strong></div><div><span>Screenshot requests · this view</span><strong>${pending.length}</strong></div></div>
   <section class="wl-panel"><form class="wl-filters" data-wl-filters><label>${talent?'Client placement':'Talent / client'}<select name="placementId"><option value="">All placements</option>${v.placements.map(p=>`<option value="${p.id}"${filters.placementId===p.id?' selected':''}>${esc(talent?p.clientName:p.talentName+' · '+p.clientName)}${p.status==='ended'?' (ended)':''}</option>`).join('')}</select></label><label>From work date<input type="date" name="from" value="${esc(filters.from||'')}"></label><label>Through work date<input type="date" name="to" value="${esc(filters.to||'')}"></label><button class="wl-button" type="submit">Apply filters</button></form>
   ${v.placements.some(p=>p.canRequest)?'<div class="wl-request-bar"><p>Need a work screenshot? Ask Talent to share an approved image for a specific work date.</p><button class="wl-button is-primary" data-wl="request">Request screenshot</button></div>':''}
   ${pending.length?`<section class="wl-requests" aria-label="Screenshot requests"><h2>Requested screenshots <span>${pending.length}</span></h2>${pending.map(r=>{const p=getp(r.placementId);return `<article><div><strong>${esc(talent?p.clientName:p.talentName)} · ${esc(r.workDate)}</strong><p>${esc(r.note||'Please share a work screenshot for this date.')}</p><small>${esc(time(r.createdAt,r.timezone||'Asia/Manila'))}</small></div>${talent&&p.canShare?`<button class="wl-button" data-wl="share" data-request="${r.id}">Share screenshot</button>`:p.canRequest?`<button class="wl-button" data-wl="cancel" data-id="${r.id}">Cancel request</button>`:''}</article>`;}).join('')}</section>`:''}
   <div class="wl-section-heading"><h2>Work sessions</h2><span>${v.total} recorded ${v.total===1?'session':'sessions'}</span></div>
   <p class="wl-note">Start Day and Check Out are manual entries—not sign-in activity, automatic productivity verification, or payroll hours. Times use each session’s recorded time zone. Open-session elapsed time is shown as of the last refresh.</p>
   ${!v.sessions.length?`<div class="wl-empty"><strong>${v.placements.length?'No work sessions in this date range':'No matched placement available'}</strong><p>${talent?'Use Start Day and Check Out on your dashboard once your client placement is active.':'Recorded sessions will appear after your matched Talent starts their workday.'}</p></div>`:v.sessions.map(s=>{const p=getp(s.placementId),images=v.images.filter(i=>i.sessionId===s.id);return `<article class="wl-session"><div class="wl-session-title"><div><h3>${esc(talent?p.clientName:p.talentName)}</h3><p>${esc(s.workDate)} · ${esc(s.timezone)}${!talent?' · '+esc(p.clientName):''}</p></div><span class="wl-status${stale(s,v.generatedAt)?' is-warning':''}">${s.checkedOutAt?'Checked out':stale(s,v.generatedAt)?'Check-out missing':'Session open'}</span></div><dl class="wl-times"><div><dt>Started</dt><dd>${esc(time(s.startedAt,s.timezone))}</dd></div><div><dt>Checked out</dt><dd>${esc(time(s.checkedOutAt,s.timezone))}</dd></div><div><dt>${s.checkedOutAt?'Elapsed time':'Elapsed so far'}</dt><dd>${esc(duration(s,v.generatedAt))}</dd></div></dl>${s.corrected?'<p class="wl-note">This record has been corrected by Soro.</p>':''}${stale(s,v.generatedAt)?'<p class="wl-warning">This session has been open for over 18 hours. Please ask Talent Management to review it; it is not counted as completed time.</p>':''}
     <div class="wl-shared"><div class="wl-section-heading"><h4>Shared screenshots <span>${images.length}</span></h4>${talent&&p.canShare?`<button class="wl-button" data-wl="share" data-session="${s.id}">Share screenshot</button>`:''}</div>${images.length?images.map(i=>`<div class="wl-image-row"><div><strong>Work screenshot</strong><p>${esc(i.note||'Shared by Talent')}</p><small>Shared ${esc(time(i.sharedAt,s.timezone))}</small></div><button class="wl-button" data-wl="image" data-id="${i.id}">View image</button>${talent?`<button class="wl-link" data-wl="withdraw" data-id="${i.id}">Withdraw</button>`:''}</div>`).join(''):'<p class="wl-note">No screenshots shared for this session.</p>'}</div></article>`;}).join('')}
   <footer class="wl-pagination"><span>${v.total?`${v.offset+1}–${Math.min(v.offset+v.sessions.length,v.total)} of ${v.total}`:'0 sessions'} · Updated ${esc(time(v.generatedAt))}</span><div><button class="wl-button" data-wl="previous"${v.offset===0?' disabled':''}>Previous</button><button class="wl-button" data-wl="next"${v.offset+v.sessions.length>=v.total?' disabled':''}>Next</button></div></footer></section><p class="wl-note">Screenshots are voluntary, manually selected uploads. Only share work your client permits. Remove passwords, patient/customer details, and other confidential information before uploading.</p></main>`;
 }
 function closeDialog(){activeMutation=null;busy=false;if(objectURL){root.URL.revokeObjectURL(objectURL);objectURL=null;}if(dialog){dialog.close();dialog.remove();dialog=null;}}
 function unmount(){generation++;controller?.abort();controller=null;closeDialog();host=null;workspace=null;busy=false;}
 async function request(method,body,query={}){
  const context={host,generation,controller,scope:scope(),client:root.soroSupabase};
  const current=()=>context.host===host&&host?.isConnected&&context.generation===generation&&context.controller===controller&&context.scope===scope()&&context.client===root.soroSupabase;
  const check=()=>{if(!current())throw Object.assign(new Error('The work log changed. Reopen it to continue.'),{name:'AbortError'});};
  if(options.adapter){const result=await options.adapter(method,body,query);check();return result;}
  if(options.preview||root.adminPreviewingNonAdminWorkspace?.())throw new Error('Work logs are private. This workspace preview does not load live records.');
  const before=context.scope,client=context.client;
  const {data:{session}={},error}=await client?.auth?.getSession?.()||{};
  check();if(error||!session?.access_token||!session.user?.id||session.user.id!==actual().user_id||actual().active===false||actual().must_change_password===true||scope()!==before||root.soroSupabase!==client)throw new Error('Sign in again to continue.');
  const response=await root.fetch(ENDPOINT+(Object.keys(query).length?'?'+new URLSearchParams(query):''),{method,headers:{Authorization:'Bearer '+session.access_token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:context.controller?.signal});
  const data=await response.json();check();
  if(!response.ok)throw new Error(data.message||'The work log could not be loaded.');return data;
 }
 async function load(){const target=host,version=++generation;controller?.abort();controller=new root.AbortController();busy=false;target.setAttribute('aria-busy','true');try{const v=validate(await request('GET',null,options.filters||{}));if(target!==host||!host?.isConnected||version!==generation)return;if(v.viewerRole!==(options.role||actual().role))throw new Error('The work log account could not be verified.');workspace=v;if(v.from&&v.to)options.filters={...options.filters,from:v.from,to:v.to};host.innerHTML=markup(v,options.filters);bind();}catch(e){if(target!==host||version!==generation||e.name==='AbortError')return;host.innerHTML=`<main class="page work-log"><h1>Work Log</h1><p role="alert">${esc(e.message)}</p><button class="wl-button" data-wl="refresh">Try again</button></main>`;bind();}finally{target?.removeAttribute('aria-busy');}}
 function mount(target,opts={}){unmount();host=target;options={...opts,filters:{...opts.filters}};if(!host)return;host.innerHTML='<main class="page work-log"><h1>Work Log</h1><p role="status">Loading recorded work sessions…</p></main>';load();}
 function modal(title,content){closeDialog();dialog=root.document.createElement('dialog');dialog.className='wl-dialog';dialog.setAttribute('aria-label',title);dialog.innerHTML=`<header><h2>${esc(title)}</h2><button class="wl-button" data-close aria-label="Close">×</button></header>${content}`;root.document.body.append(dialog);dialog.querySelector('[data-close]').onclick=closeDialog;dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.showModal();return dialog;}
 function alertIn(d,e){const node=d.querySelector('[role=alert]');if(node)node.textContent=e.message||'Please try again.';}
 async function mutate(body,d){if(busy)return;const target=host,version=generation,operation={};activeMutation=operation;const current=()=>activeMutation===operation&&host===target&&generation===version&&dialog===d&&d?.isConnected;busy=true;d?.querySelectorAll('button').forEach(b=>b.disabled=true);try{const v=await request('POST',body);if(!current())return;closeDialog();await load();return v;}catch(e){if(current()&&e.name!=='AbortError'){alertIn(d,e);d.querySelectorAll('button').forEach(b=>b.disabled=false);}}finally{if(activeMutation===operation){activeMutation=null;busy=false;}}}
 function requestDialog(){const eligible=workspace.placements.filter(p=>p.canRequest);const d=modal('Request a work screenshot',`<form><label>Talent / placement<select name="placementId">${eligible.map(p=>`<option value="${p.id}">${esc(p.talentName+' · '+p.clientName)}</option>`).join('')}</select></label><label>Work date<input type="date" name="workDate" required value="${new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila'}).format(new Date())}"></label><p class="wl-note">Use the Talent’s work date. This creates a request in their Work Log, not an automatic screen capture.</p><label>What would you like to see? (optional)<textarea name="note" maxlength="500" rows="3"></textarea></label><p role="alert"></p><footer><button class="wl-button is-primary" type="submit">Send request</button></footer></form>`);const requestId=root.crypto.randomUUID();d.querySelector('form').onsubmit=e=>{e.preventDefault();const form=new root.FormData(e.target);mutate({action:'request',requestId,placementId:form.get('placementId'),workDate:form.get('workDate'),note:form.get('note')},d);};}
 function shareDialog(button){const req=workspace.requests.find(r=>r.id===button.dataset.request);const sessions=workspace.sessions.filter(s=>(!button.dataset.session||s.id===button.dataset.session)&&(!req||s.placementId===req.placementId&&s.workDate===req.workDate)&&workspace.placements.find(p=>p.id===s.placementId)?.canShare);if(!sessions.length){modal('Choose a recorded work session','<p>No matching session is on this page. Filter the Work Log to the request’s date and placement, then choose Share screenshot on that session.</p>');return;}
  const d=modal('Share a work screenshot',`<form><label>Work session<select name="sessionId">${sessions.map(s=>`<option value="${s.id}">${esc(s.workDate+' · '+workspace.placements.find(p=>p.id===s.placementId).clientName)}</option>`).join('')}</select></label><label>Screenshot<input type="file" name="image" accept="image/png,image/jpeg,image/webp" required></label><p class="wl-note">PNG, JPG, or WebP · up to 3 MB. Preview and remove confidential information before sharing.</p><img class="wl-image-preview" alt="Your selected screenshot preview" hidden><label>Work summary (optional)<textarea name="note" maxlength="500" rows="3"></textarea></label><label class="wl-confirm"><input type="checkbox" required> I have reviewed this screenshot and approve sharing it with the client named above.</label><p role="alert"></p><footer><button class="wl-button is-primary" type="submit">Share with client</button></footer></form>`);
  let file;const input=d.querySelector('[type=file]'),preview=d.querySelector('img');input.onchange=()=>{if(objectURL)root.URL.revokeObjectURL(objectURL);file=input.files?.[0];preview.hidden=true;if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3145728||!file.size){file=null;input.value='';alertIn(d,new Error('Choose a PNG, JPG, or WebP up to 3 MB.'));return;}objectURL=root.URL.createObjectURL(file);preview.src=objectURL;preview.hidden=false;};
  const requestId=root.crypto.randomUUID();d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!file||busy)return;const chosen=file;try{const reader=new root.FileReader(),base64=await new Promise((resolve,reject)=>{reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(chosen);});if(!d.isConnected)return;if(file!==chosen)throw new Error('The selected image changed. Review it and choose Share again.');const form=new root.FormData(e.target);await mutate({action:'share',requestId,sessionId:form.get('sessionId'),note:form.get('note'),image:{type:chosen.type,dataBase64:base64}},d);}catch(error){alertIn(d,error);}};
 }
 async function imageDialog(id){const d=modal('Shared work screenshot','<p role="status">Opening private image…</p><p role="alert"></p>');try{const v=await request('GET',null,{imageId:id});if(!d.isConnected||dialog!==d)return;const url=new URL(v.url),origin=new URL(root.SORO_SUPABASE_CONFIG.url).origin;if(url.protocol!=='https:'||url.origin!==origin||!url.pathname.startsWith('/storage/v1/object/sign/soro-work-evidence/'))throw new Error('The image link could not be verified.');const img=root.document.createElement('img');img.alt='Work screenshot shared by Talent';img.className='wl-image-preview';img.referrerPolicy='no-referrer';img.src=url.href;img.onerror=()=>{if(d.isConnected)alertIn(d,new Error('The image link expired or could not load. Close this window and choose View image again.'));};d.querySelector('[role=status]').replaceWith(img);}catch(e){if(d.isConnected)alertIn(d,e);}}
 function bind(){host.onsubmit=e=>{if(!e.target.matches('[data-wl-filters]'))return;e.preventDefault();options.filters=Object.fromEntries([...new root.FormData(e.target)].filter(([,v])=>v));load();};host.onclick=e=>{const b=e.target.closest('[data-wl]');if(!b||busy)return;const action=b.dataset.wl;if(action==='refresh')load();if(action==='next'||action==='previous'){options.filters.offset=String(Math.max(0,(workspace?.offset||0)+(action==='next'?30:-30)));load();}if(action==='request')requestDialog();if(action==='share')shareDialog(b);if(action==='image')imageDialog(b.dataset.id);if(action==='cancel'||action==='withdraw'){const d=modal(action==='cancel'?'Cancel screenshot request?':'Withdraw this screenshot?',`<p>${action==='cancel'?'Talent will no longer see this as a pending request.':'The client will no longer be able to open this image. A link already opened may work for up to 60 seconds.'}</p><p role="alert"></p><footer><button class="wl-button is-primary" data-confirm>Confirm</button></footer>`);d.querySelector('[data-confirm]').onclick=()=>mutate({action,id:b.dataset.id,requestId:root.crypto.randomUUID()},d);}};}
 root.addEventListener?.('soro-auth-changed',()=>{const target=host;unmount();target?.replaceChildren();});
 return Object.freeze({mount,unmount,markup,validate,duration,stale,ROLES,day});
});
