/* Runs only in an opaque sandbox. All state is fictional and is discarded on exit. */
(function(w){
  'use strict';
  if(w.parent===w)return;
  const id=n=>`f0000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
  const clone=v=>JSON.parse(JSON.stringify(v));
  const now=()=>new Date().toISOString();
  const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const personas={client:{role:'client_admin',name:'Alex Carter',id:id(1)},talent:{role:'talent_management',name:'Taylor Morgan',id:id(2)},sales:{role:'sales',name:'Jordan Lee',id:id(3)},va:{role:'virtual_assistant',name:'Jamie Cruz',id:id(4)}};
  let selected='client',store;
  function reset(){
    store={contactName:'Alex Carter',companyName:'Sample Company',tasks:[],stage:'submitted',recorded:false,verified:[],workday:'not_started'};
    store.applicants=[{id:id(10),organization_id:id(90),auth_user_id:id(4),full_name:'Cruz, Jamie',first_name:'Jamie',last_name:'Cruz',preferred_name:'Jamie',email:'jamie@example.test',phone:'',application_status:'submitted',review_status:'submitted',application_received_at:now(),created_at:now(),updated_at:now(),archived_at:null,country:'Philippines',time_zone:'Asia/Manila',current_work_status:'Available',availability:'Full time',skills:['Calendar management','Email management','Medical coding'],verified_skills:[],work_areas:['General Virtual Assistance','Medical & Healthcare'],experience_years:3,experience_summary:'Fictional profile for reviewing the current Talent Portal.',dream_goal:'Build a long-term career supporting a team.',english_test_result:'',personality_test_result:'',computer_specifications:'',internet_speed:'',review_owner_id:id(2)}];
    store.applicants[0].self_reported_skills=store.applicants[0].skills.slice();
    Object.assign(store.applicants[0],{status:'submitted',work_status:'Available',timezone:'Asia/Manila',english_proficiency_score:'',personality_profile_score:'',computer_specs:'',legacy_application_data:{}});
    store.applicants[0].verified_skills=['Calendar management','Email management'];
    store.applicants.push({...clone(store.applicants[0]),id:id(11),auth_user_id:null,full_name:'Santos, Riley',first_name:'Riley',last_name:'Santos',preferred_name:'Riley',email:'riley@example.test',verified_skills:[]});
    store.clients=[{id:id(50),company:{name:store.companyName,industry:'Professional services',website:'example.test',country:'United States'},primaryContact:{name:store.contactName,title:'Owner',email:'alex@example.test',phone:''},owner:{id:id(3),name:'Jordan Lee',current:true},lifecycleStage:'active',portal:{requested:true,status:'active',email:'alex@example.test'},hiringRequests:[{id:id(20),roleTitle:'General Virtual Assistant',vaType:'General',seats:1,skills:['Calendar management','Email management'],schedule:'Monday–Friday · Philippine Time',timeZone:'Asia/Manila',targetStartDate:day(),status:'filled',progressStep:'active',candidateCount:0}],activity:[{label:'Sample account',detail:'Fictional data for Test Mode.',timestamp:now()}]}];
    store.tasks=[{id:id(30),title:'Review your sample profile',details:'Check your details and let your Soro team know if anything needs updating. This is a fictional task.',kind:'manual',version:1,progress:'not_started',status:'open',priority:'normal',dueDate:day(),createdAt:now(),updatedAt:now(),relatedLabel:'Sample Talent Profile',isUnread:true,assignees:[{id:id(4),userId:id(4),name:'Jamie Cruz'}],assignedTo:{id:id(4),name:'Jamie Cruz'},createdBy:{id:id(2),name:'Taylor Morgan'},history:[]}];
    store.tasks.push({...clone(store.tasks[0]),id:id(31),title:'Review client requirements',details:'Check the sample Client account and its role requirements.',relatedLabel:'Sample Company',assignees:[{id:id(3),userId:id(3),name:'Jordan Lee'}],assignedTo:{id:id(3),name:'Jordan Lee'},createdBy:{id:id(3),name:'Jordan Lee'}});
  }
  reset();
  const notice=message=>w.parent.postMessage({type:'soro-test-notice',message},'*');
  const unavailable=()=>{notice('This action is not available in Test Mode. No live request was sent.');return{error:{message:'Not available in Test Mode. No live request was sent.'},data:null};};
  function access(){const p=personas[selected];return{role:p.role,display_name:p.name,user_id:p.id,id:p.id,organization_id:id(90),active:true,is_founder:false,must_change_password:false};}
  function query(table){
    const filters=[];let single=false,mutation=null;
    const captured=store,actor=selected;
    const api={select(){return api;},eq(k,v){filters.push(r=>r[k]===v);return api;},neq(k,v){filters.push(r=>r[k]!==v);return api;},not(){return api;},is(k,v){filters.push(r=>(r[k]??null)===v);return api;},in(k,v){filters.push(r=>v.includes(r[k]));return api;},order(){return api;},limit(){return api;},range(){return api;},maybeSingle(){single=true;return api;},single(){single=true;return api;},update(v){mutation=v;return api;},insert(){mutation=false;return api;},delete(){mutation=false;return api;},then(resolve,reject){try{if(captured!==store||actor!==selected)return Promise.resolve(unavailable()).then(resolve,reject);let rows=table==='applicants'?store.applicants:table==='platform_users'?[access()]:[];if(table==='applicants'&&selected==='va')rows=rows.filter(a=>a.auth_user_id===personas.va.id);if(table==='applicants'&&selected==='client')rows=[];rows=rows.filter(row=>filters.every(f=>f(row)));if(mutation!==null){if(table!=='applicants'||selected!=='talent'||!mutation)return Promise.resolve(unavailable()).then(resolve,reject);rows.forEach(row=>Object.assign(row,mutation,{updated_at:now()}));notice('Sample profile updated in this test session only.');}return Promise.resolve({data:clone(single?(rows[0]||null):rows),error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return api;
  }
  w.soroSupabase={auth:{getSession:async()=>({data:{session:{access_token:'fictional-test-session',user:{id:personas[selected].id,email:'sample@example.test'}}}}),getUser:async()=>({data:{user:{id:personas[selected].id}}}),onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}})},from:query,rpc:async()=>unavailable(),storage:{from:()=>({createSignedUrl:async()=>unavailable(),upload:async()=>unavailable(),download:async()=>unavailable()})}};
  w.soroCurrentAccess=access();
  // The parent URL and browser history are never changed by sample navigation.
  let routeState=null;
  const nativeReplace=w.history.replaceState.bind(w.history);
  for(const method of ['replaceState','pushState'])w.history[method]=(state,title,url)=>{routeState=state;const hash=String(url||'').includes('#')?'#'+String(url).split('#').slice(1).join('#'):'';nativeReplace(state,title,'about:srcdoc'+hash);};
  try{Object.defineProperty(w.history,'state',{get:()=>routeState});}catch{}
  function dashboard(){return{generatedAt:now(),viewerRole:personas[selected].role,companyName:store.companyName,contactName:store.contactName,salesContact:{name:'Jordan Lee',email:'jordan@example.test',phone:''},requests:[{requestId:id(20),roleTitle:'General Virtual Assistant',status:'filled',targetStartDate:day(),seatCount:1,candidateCount:0,pendingReviewCount:0,pendingDecisionCount:0,placementCount:1,activePlacementCount:1,onboardingCount:0}],interviews:[],talent:[{placementId:id(21),applicantId:id(10),fullName:'Jamie Cruz',preferredName:'Jamie',roleTitle:'General Virtual Assistant',status:'active',startDate:day(),scheduleSummary:'Monday–Friday · 9 AM–5 PM Philippine Time'}]};}
  function queue(){const a=store.applicants[1],keys=['core_profile','resume','english','disc','enneagram','mbti','internet','equipment','skills'],labels=['Core profile','Resume','English assessment','DISC assessment','Enneagram assessment','Four-letter personality assessment','Internet speed proof','Computer specifications','Applicant-reported skills'];const personality=w.soroScreeningPresentation?.parsePersonalityResults(a.personality_profile_score)||{};const values={english:a.english_test_result,disc:personality.disc,enneagram:personality.enneagram,mbti:personality.mbti,internet:a.internet_speed,equipment:a.computer_specs};return{generatedAt:now(),viewerRole:personas[selected].role,summary:{all:1,submitted:store.stage==='submitted'?1:0,in_review:store.stage==='in_review'?1:0,needs_more_info:store.stage==='needs_more_info'?1:0,bench_ready:0,closed:0},applicants:[{applicantId:a.id,fullName:a.full_name,email:a.email,applicationReceivedAt:a.application_received_at,updatedAt:a.updated_at,stage:store.stage,archived:false,owner:{id:id(2),name:'Taylor Morgan'},resume:{available:false,label:'No sample résumé'},checklist:keys.map((key,i)=>({key,label:labels[i],state:key==='resume'?'missing':'complete',...(i>=2&&i<=7?{resultRecorded:Boolean(values[key]),evidenceState:'available'}:{}),...(key==='skills'?{verifiedSkillsCount:a.verified_skills.length}:{})})),allowedActions:store.stage==='submitted'?['begin_review']:['request_more_info']}]};}
  function taskWorkspace(){const actor=personas[selected].id,tasks=store.tasks.filter(t=>t.assignees.some(p=>p.id===actor)||t.createdBy.id===actor).map(t=>({...t,isNew:!t.viewedBy?.includes(actor)}));return{tasks,notifications:[],assignees:Object.values(personas).filter(p=>['sales','talent_management'].includes(p.role)).map(p=>({id:p.id,userId:p.id,name:p.name,role:p.role})),summary:{open:tasks.filter(t=>t.status!=='completed').length,overdue:0,urgentUnread:0}};}
  function clientTalent(){const a=store.applicants[0];return{talents:[{id:a.id,displayName:a.full_name,location:{country:a.country,timeZone:a.time_zone},skills:{verified:a.verified_skills},experience:{years:a.experience_years,summary:a.experience_summary},screening:{englishResult:'',personalityResult:'',computerSpecifications:'',internetSpeed:''},assignments:[{id:id(21),status:'active',startDate:day(),scheduleSummary:'Monday–Friday · Philippine Time'}]}]};}
  function clientProfile(){const c=store.clients[0];return{profile:{contact:{fullName:c.primaryContact.name,phone:c.primaryContact.phone},company:c.company,signInEmail:'alex@example.test'},permissions:{canEditCompany:true}};}
  function tracker(){return{generatedAt:now(),viewerRole:personas[selected].role,rows:store.clients.flatMap(c=>c.hiringRequests.map(r=>({clientId:c.id,clientName:c.company.name,requestId:r.id,roleTitle:r.roleTitle,ownerId:id(3),ownerName:'Jordan Lee',status:r.status,stage:r.status==='filled'?'active':'matching',candidateCount:0,interviewCount:0,placementCount:r.status==='filled'?1:0,seatCount:1,activePlacementCount:r.status==='filled'?1:0,onboardingCount:0,targetStartDate:day(),lastActivityAt:now(),nextInterviewAt:'',attentionCode:'',nextAction:r.status==='filled'?'view_placement':'find_candidates',responsibleRole:'sales'})))};}
  function checkins(method,body,u){
    if(!['talent','sales'].includes(selected)||u.searchParams.has('applicantId')&&selected==='sales')return null;
    const actor=personas[selected],side=selected==='sales'?'client':'talent';
    if(method==='GET'&&!(u.searchParams.get('placementId')===id(21)||u.searchParams.get('applicantId')===id(10)))return null;
    store.checkins||={plans:[],notes:[],requests:[]};const state=store.checkins;
    function task(plan){let t=store.tasks.find(t=>t.source?.planId===plan.id&&t.status==='open');if(!plan.enabled){if(t){t.status='completed';t.progress='completed';t.source.state='cancelled';}return;}if(!t){t={id:crypto.randomUUID(),title:'Complete '+(side==='client'?'Client':'Talent')+' check-in',details:'Fictional check-in reminder. Record an outcome in Check-ins.',kind:'staff_task',version:1,progress:'not_started',status:'open',priority:'normal',createdAt:now(),updatedAt:now(),createdBy:{id:actor.id,name:actor.name},relatedLabel:'Jamie Cruz · Sample Company',history:[],source:{kind:'placement_checkin',placementId:id(21),applicantId:id(10),planId:plan.id,side,state:'open'}};store.tasks.push(t);}t.dueDate=plan.nextDue;t.assignees=[{id:actor.id,userId:actor.id,name:actor.name}];t.assignedTo={userId:actor.id,name:actor.name};}
    if(method==='POST'&&!state.requests.includes(body.requestId)){
      if(body.placementId!==id(21)||body.side!==side)return null;
      if(body.action==='schedule'){let p=state.plans.find(p=>p.side===side);if((p?.version||0)!==body.version||body.ownerId!==actor.id)return null;if(!p){p={id:crypto.randomUUID(),placementId:id(21),clientName:store.companyName,side,version:0};state.plans.push(p);}Object.assign(p,{ownerId:actor.id,ownerName:actor.name,cadenceDays:body.cadenceDays,nextDue:body.nextDue,enabled:body.enabled,version:p.version+1});task(p);}
      else if(['record','correct'].includes(body.action)){const old=state.notes.find(n=>n.id===body.noteId),p=state.plans.find(p=>p.id===body.planId);if(body.action==='correct'&&(!old||old.side!==side||old.version!==body.version))return null;if(body.planId&&(!p||!p.enabled||p.version!==body.planVersion))return null;const note={...body,id:old?.id||crypto.randomUUID(),placementId:id(21),clientName:store.companyName,authorName:actor.name,recordedAt:now(),version:(old?.version||0)+1,revisions:old?[{...clone(old),revisions:[]},...old.revisions]:[]};state.notes=state.notes.filter(n=>n.id!==note.id);state.notes.unshift(note);if(p){const t=store.tasks.find(t=>t.source?.planId===p.id&&t.status==='open');if(t){t.status='completed';t.progress='completed';t.source.state='completed';}const d=new Date(day()+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+p.cadenceDays);p.nextDue=d.toISOString().slice(0,10);p.enabled=p.cadenceDays>0;p.version++;task(p);}}
      else return null;state.requests.push(body.requestId);notice('Sample check-in saved. Private notes are visible only to authorized sample staff.');
    }
    const notes=state.notes.filter(n=>(selected==='talent'||n.side==='client')&&(!u.searchParams.get('kind')||n.kind===u.searchParams.get('kind'))&&(!u.searchParams.get('from')||n.observedOn>=u.searchParams.get('from'))&&(!u.searchParams.get('to')||n.observedOn<=u.searchParams.get('to'))),offset=Number(u.searchParams.get('offset')||0);
    return{viewerRole:actor.role,subject:u.searchParams.has('applicantId')?'talent':'placement',talentName:'Jamie Cruz',today:day(),placements:[{id:id(21),clientName:store.companyName,canRecord:true,canSchedule:true,sides:[side],owners:[{id:actor.id,name:actor.name,sides:[side]}]}],plans:state.plans.filter(p=>selected==='talent'||p.side==='client').map(p=>({...p,canManage:p.side===side})),notes:notes.slice(offset,offset+30).map(n=>({...n,canCorrect:n.side===side})),total:notes.length};
  }
  async function dispatch(url,options={}){
    const u=new URL(typeof url==='string'?url:url.url,'https://test.invalid'),name=u.pathname.split('/').pop();let body={};try{body=JSON.parse(options.body||'{}');}catch{}
    const method=options.method||'GET';let result;
    // Only listed local API paths are modeled. Even a matching basename on an external URL is rejected.
    if(u.origin!=='https://test.invalid'||!u.pathname.startsWith('/.netlify/functions/'))return new Response(JSON.stringify({message:'External services are disabled in Test Mode.'}),{status:403});
    if(name==='placement-checkins'){result=checkins(method,body,u);if(!result)return new Response(JSON.stringify({message:'This sample role or record cannot perform this check-in action.'}),{status:403});}
    else if(name==='client-dashboard'&&method==='GET')result=dashboard();
    else if(name==='talent-review-queue'&&method==='GET')result=queue();
    else if(name==='talent-verification'&&method==='GET'&&selected==='talent'){const a=queue().applicants[0];result={generatedAt:now(),viewerRole:personas[selected].role,applicant:a,gate:{interviewAddressed:false,referencesAddressed:false,benchReadyEligible:false,blockers:['Interview and reference review are still pending.']},interview:null,interviewHistory:[],references:[],interviewers:[{id:id(2),name:'Taylor Morgan'}],availableAttendees:[{id:id(3),name:'Jordan Lee'}],calendarIntegration:{configured:false,organizerLabel:'Disabled in Test Mode'}};}
    else if(name==='talent-review-queue'&&method==='POST'&&body.action==='begin_review'&&selected==='talent'){store.stage='in_review';store.applicants[1].updated_at=now();result=queue();}
    else if((name==='tasks'&&method==='GET')||(name==='task-detail'&&body.action==='workspace'))result=taskWorkspace();
    else if(name==='task-detail'&&body.action==='create'&&['talent','sales'].includes(selected)){const p=body.patch||{},task={id:crypto.randomUUID(),kind:'manual',version:1,...p,status:'open',isUnread:true,progress:'not_started',createdAt:now(),updatedAt:now(),createdBy:{id:personas[selected].id,name:personas[selected].name},history:[],assignees:Object.values(personas).filter(x=>(p.assigneeIds||[]).includes(x.id)).map(x=>({id:x.id,userId:x.id,name:x.name}))};store.tasks.push(task);result={task};notice('Sample task created. It exists only in this Test Mode session.');}
    else if(name==='task-detail'&&['get','view','save'].includes(body.action)){
      const task=taskWorkspace().tasks.some(t=>t.id===body.taskId)&&store.tasks.find(t=>t.id===body.taskId);if(!task)return new Response('{}',{status:404});
      if(body.action==='view'){task.isUnread=false;task.viewedBy=[...new Set([...(task.viewedBy||[]),personas[selected].id])];}
      if(body.action==='save'){if(task.source?.kind==='placement_checkin')return new Response('{}',{status:403});const p=body.patch||{};for(const key of (selected==='va'?['progress']:['title','details','relatedLabel','dueDate','priority','progress']))if(Object.hasOwn(p,key))task[key]=p[key];task.status=task.progress==='completed'?'completed':'open';task.version++;task.history.unshift({actor:personas[selected].name,at:now(),summary:'Sample task updated',note:p.note||''});notice('Sample task saved. Switch views to inspect the shared update.');}
      result={task:{...task,canUpdateProgress:task.source?.kind!=='placement_checkin',canEditDetails:selected!=='va'&&task.source?.kind!=='placement_checkin',canAssign:false},history:task.history,assignees:taskWorkspace().assignees};
    }
    else if(name==='client-profile'&&selected==='client'){if(method==='PATCH'){const c=store.clients[0];Object.assign(c.company,body.company||{});if(body.contact?.fullName)c.primaryContact.name=body.contact.fullName;if(Object.hasOwn(body.contact||{},'phone'))c.primaryContact.phone=body.contact.phone;store.contactName=c.primaryContact.name;store.companyName=c.company.name;notice('Sample account details saved. The Sales view uses this same sample account.');}result=clientProfile();}
    else if(name==='client-talent-profile'&&method==='GET'&&selected==='client')result=clientTalent();
    else if(name==='sales-lifecycle-tracker'&&method==='GET'&&selected==='sales')result=tracker();
    else if(name==='available-talent-bench'&&method==='GET')result={generatedAt:now(),viewerRole:personas[selected].role,items:[],salesOwners:[{id:id(3),name:'Jordan Lee',claimed:0,capacity:10}],caseload:{ownerId:id(3),claimed:0,capacity:10,remaining:10}};
    else if(name==='client-shortlists'&&method==='GET')result={generatedAt:now(),viewerRole:personas[selected].role,hiringRequests:[],candidates:[],notifications:[]};
    else if(name==='document-center'&&method==='GET')result=u.searchParams.has('notifications')?{count:0}:{internal:['sales','talent'].includes(selected),canManageTemplates:false,requests:[],files:[],templates:[],packets:[],total:0,hasMore:false};
    else if(name==='support-tickets'&&method==='GET')result=u.searchParams.has('notifications')?{unread:0}:{tickets:[],total:0,hasMore:false,internal:['sales','talent'].includes(selected),isAdmin:false,team:personas[selected].role,summary:{}};
    else if(name==='work-log'&&method==='GET')result={generatedAt:now(),viewerRole:personas[selected].role,placements:[{id:id(21),talentName:'Jamie Cruz',clientName:store.companyName,status:'active',canShare:selected==='va',canRequest:selected==='client'}],sessions:store.workday==='not_started'?[]:[{id:id(22),placementId:id(21),workDate:store.workDate,startedAt:store.startedAt,checkedOutAt:store.checkedOutAt||null,timezone:'Asia/Manila'}],requests:[],images:[],total:store.workday==='not_started'?0:1,offset:0};
    else if(name==='active-talent-today'&&method==='GET')result={generatedAt:now(),summary:{activeTalent:0,checkedInToday:0,workingNow:0,completedToday:0,notStarted:0,needsReview:0},rows:[]};
    else if(name==='operations-reports'&&method==='GET')result={generatedAt:now(),role:personas[selected].role,report:u.searchParams.get('report'),rows:[],total:0,offset:0,summary:{total:0,statuses:{},flags:{}},options:{owners:[],statuses:[],teams:[],areas:[]}};
    else if(name==='talent-attendance'&&selected==='va'){
      if(method==='POST'&&body.action==='start_day'&&store.workday==='not_started'){store.workday='started';store.startedAt=now();store.workDate=day();notice('Sample workday started. No live attendance was recorded.');}
      if(method==='POST'&&body.action==='check_out'&&store.workday==='started'){store.workday='completed';store.checkedOutAt=now();notice('Sample workday completed. No live attendance was recorded.');}
      result={state:store.workday,eligible:true,applicantId:id(10),placementId:id(21),sessionId:id(22),clientName:store.companyName,scheduleSummary:'Monday–Friday · 9 AM–5 PM Philippine Time',workDate:store.workDate||day(),workTimezone:'Asia/Manila',startedAt:store.startedAt||'',checkedOutAt:store.checkedOutAt||''};
    }
    else if(name==='global-search')result={groups:[],results:[]};
    else {if(method!=='GET')unavailable();return new Response(JSON.stringify({message:'Not available in Test Mode. No live request was sent.'}),{status:409,headers:{'Content-Type':'application/json'}});}
    return new Response(JSON.stringify(result),{headers:{'Content-Type':'application/json'}});
  }
  // There is deliberately no reference to native fetch and no network fallback.
  w.fetch=dispatch;
  w.XMLHttpRequest=function(){throw new Error('Network is disabled in Test Mode.');};
  w.WebSocket=w.EventSource=w.Worker=function(){throw new Error('External services are disabled in Test Mode.');};
  w.open=()=>{notice('External links and file downloads are disabled in Test Mode.');return null;};
  document.addEventListener('click',event=>{const a=event.target.closest('a');if(a&&a.getAttribute('href')&&!a.getAttribute('href').startsWith('#')){event.preventDefault();event.stopImmediatePropagation();notice('External links are disabled in Test Mode.');}},true);
  // Opaque sandbox origins intentionally cannot use browser storage. Supply only disposable preferences.
  for(const key of ['localStorage','sessionStorage']){const memory=new Map();try{Object.defineProperty(w,key,{value:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k),clear:()=>memory.clear()}});}catch{}}
  w.SoroTestSession={id,personas,access,queue,dashboard,get store(){return store;},get selected(){return selected;},select(value){if(personas[value])selected=value;},reset,notice};
}(window));
